### ISSUE TITLE
Native crash when using ImageIO#read on AIX AdoptOpenJDK J9

### ISSUE THREAD

**Issue by mvdobrinin** [eclipse/openj9#5530]
Java -version output
--------------------

```
>java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.12.1, JRE 11 AIX ppc64-64-Bit Compressed References 20190204_121 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb
OMR      - d2f4534
JCL      - 289c70b based on jdk-11.0.2+9)
```

OS version output
--------------------
```
>uname -s
AIX
>oslevel -s
7200-03-02-1846
```

Summary of problem
------------------

There is a native crash occurring in the JVM when attempting to read an image. I can reproduce the issue with a fairly simple Java app, though it does require me to load some native libraries. I am still working to identify it there is a specific native library that reveals this issue. The conditions seem to be the following -

1. The Java class loads some native libraries via `System.loadLibrary()`. Without this, step 2 works without issues.
2. The Java class calls `javax.imageio.ImageIO#read(java.io.File)`. This Java method internally loads some native libraries in the JVM (due to static initializer in java.awt.Toolkit class). This line causes the JVM to crash.

Diagnostic files
----------------
Standard error -
```
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000033
Handler1=09001000A04A3790 Handler2=09001000A0479BF0
R0=0000000000000000 R1=0000000110059680 R2=09001000A053E018 R3=0000000000000000
R4=09000000072C131B R5=FFFFFFFFFFFFFFFF R6=000000000000002F R7=000000000000006C
R8=0000000000000069 R9=0000000000000062 R10=0000000000000000 R11=0000000000000000
R12=09001000A053D008 R13=0000000110067800 R14=0000000000000000 R15=09000000025E77B8
R16=0000000000000010 R17=09001000A02FEAF0 R18=0000000126052490 R19=00000001225E1B18
R20=0000000000000000 R21=0000000110059F38 R22=00000001100D96B0 R23=0000000000000200
R24=09000000072C1308 R25=09000000072C1318 R26=00000000300F89D8 R27=00000000300F89E0
R28=0000000000000000 R29=0000000000000000 R30=000000003001B100 R31=0000000000010000
IAR=0900000002A0FBC8 LR=09000000072B93C4 MSR=A00000000200D032 CTR=00000000000003FF
CR=4442024400000000 FPSCR=8200000000000000 XER=0000000082000000
FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR1 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
FPR2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR3 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
FPR4 4330000000000000 (f: 0.000000, d: 4.503600e+15)
FPR5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR7 3f0ec135f9ea50c3 (f: 4192882944.000000, d: 5.865999e-05)
FPR8 bfb96bfae093ca0d (f: 3767781888.000000, d: -9.930389e-02)
FPR9 40fb39343ff01715 (f: 1072699136.000000, d: 1.115073e+05)
FPR10 007200650073006f (f: 7536751.000000, d: 1.602190e-306)
FPR11 3fbc73cd95d5986d (f: 2513803264.000000, d: 1.111420e-01)
FPR12 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
FPR13 4085fd5560000000 (f: 1610612736.000000, d: 7.036667e+02)
FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Target=2_90_20190204_121 (AIX 7.2)
CPU=ppc64 (32 logical CPUs) (0x7c0000000 RAM)
----------- Stack Backtrace -----------
(0x09000000024CA370)
(0x09000000024CB1CC)
(0x09000000024CA89C)
(0x09000000024CAB10)
(0x09000000025B8468)
(0x09000000024A447C)
(0x090000000243E894)
(0x0900000002459480)
(0x090000000245A5CC)
(0x090000000245A500)
(0x09000000024379E0)
(0x0900000002437F14)
(0x09000000025A5594)
(0x09000000024A447C)
(0x090000000243E894)
(0x0900000002459480)
(0x090000000245A5CC)
(0x09000000024379E0)
(0x0900000002437F14)
(0x09000000025A5594)
(0x09000000024A447C)
(0x0900000002441FA4)
(0x0900000002450DAC)
(0x090000000244B02C)
(0x09000000026F4E70)
(0x090000000244B17C)
(0x0900000002450D24)
(0x090000000248740C)
(0x0000000100007070)
(0x090000000054DFEC)
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2019/04/16 23:04:56 - please wait.
JVMDUMP032I JVM requested System dump using '/export/disk1/installers/app/les/test/core.20190416.230456.7274754.0001.dmp' in response to an event
Note: "Enable full CORE dump" in smit is set to FALSE and as a result there will be limited threading information in core file.
JVMDUMP010I System dump written to /export/disk1/installers/app/les/test/core.20190416.230456.7274754.0001.dmp
JVMDUMP032I JVM requested Java dump using '/export/disk1/installers/app/les/test/javacore.20190416.230456.7274754.0002.txt' in response to an event
JVMDUMP010I Java dump written to /export/disk1/installers/app/les/test/javacore.20190416.230456.7274754.0002.txt
JVMDUMP032I JVM requested Snap dump using '/export/disk1/installers/app/les/test/Snap.20190416.230456.7274754.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /export/disk1/installers/app/les/test/Snap.20190416.230456.7274754.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/export/disk1/installers/app/les/test/jitdump.20190416.230456.7274754.0004.dmp'
JVMDUMP010I JIT dump written to /export/disk1/installers/app/les/test/jitdump.20190416.230456.7274754.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".

```

Call stacks from core.txt -

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "main" J9VMThread:0x000000003001B100, omrthread_t:0x0000000110069D80, java/lang/Thread:0x00000006100B29D8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x4210217, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMCPUTIME               CPU usage total: 5.790530000 secs, user: 5.281971000 secs, system: 0.508559000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=7865528 (0x7804B8)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/ClassLoader.loadLibraryWithPath(Native Method)
4XESTACKTRACE                at java/lang/ClassLoader.loadLibraryWithPath(ClassLoader.java:1670)
4XESTACKTRACE                at java/lang/ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1643)
5XESTACKTRACE                   (entered lock: java/lang/ClassLoader@0x0000000610001408, entry count: 1)
4XESTACKTRACE                at java/lang/System.loadLibrary(System.java:559)
4XESTACKTRACE                at java/awt/Toolkit$3.run(Toolkit.java:1395)
4XESTACKTRACE                at java/awt/Toolkit$3.run(Toolkit.java:1393)
4XESTACKTRACE                at java/security/AccessController.doPrivileged(AccessController.java:647)
4XESTACKTRACE                at java/awt/Toolkit.loadLibraries(Toolkit.java:1392)
4XESTACKTRACE                at java/awt/Toolkit.<clinit>(Toolkit.java:1425)
4XESTACKTRACE                at sun/awt/AppContext$2.run(AppContext.java:282)
4XESTACKTRACE                at sun/awt/AppContext$2.run(AppContext.java:271)
4XESTACKTRACE                at java/security/AccessController.doPrivileged(AccessController.java:647)
4XESTACKTRACE                at sun/awt/AppContext.initMainAppContext(AppContext.java:271)
4XESTACKTRACE                at sun/awt/AppContext$3.run(AppContext.java:326)
5XESTACKTRACE                   (entered lock: sun/awt/AppContext$GetAppContextLock@0x00000007FF3D9E90, entry count: 1)
4XESTACKTRACE                at sun/awt/AppContext$3.run(AppContext.java:309)
4XESTACKTRACE                at java/security/AccessController.doPrivileged(AccessController.java:647)
4XESTACKTRACE                at sun/awt/AppContext.getAppContext(AppContext.java:308)
4XESTACKTRACE                at javax/imageio/spi/IIORegistry.getDefaultInstance(IIORegistry.java:129)
4XESTACKTRACE                at javax/imageio/ImageIO.<clinit>(ImageIO.java:66)
4XESTACKTRACE                at <redacted>/MediaUtils.readImage(MediaUtils.java:180)
4XESTACKTRACE                at Reproduce.main(Reproduce.java:54)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               (0x09000000024CA370)
4XENATIVESTACK               (0x09000000024CB1CC)
4XENATIVESTACK               (0x09000000024CA89C)
4XENATIVESTACK               (0x09000000024CAB10)
4XENATIVESTACK               (0x09000000025B8468)
4XENATIVESTACK               (0x09000000024A447C)
4XENATIVESTACK               (0x090000000243E894)
4XENATIVESTACK               (0x0900000002459480)
4XENATIVESTACK               (0x090000000245A5CC)
4XENATIVESTACK               (0x090000000245A500)
4XENATIVESTACK               (0x09000000024379E0)
4XENATIVESTACK               (0x0900000002437F14)
4XENATIVESTACK               (0x09000000025A5594)
4XENATIVESTACK               (0x09000000024A447C)
4XENATIVESTACK               (0x090000000243E894)
4XENATIVESTACK               (0x0900000002459480)
4XENATIVESTACK               (0x090000000245A5CC)
4XENATIVESTACK               (0x09000000024379E0)
4XENATIVESTACK               (0x0900000002437F14)
4XENATIVESTACK               (0x09000000025A5594)
4XENATIVESTACK               (0x09000000024A447C)
4XENATIVESTACK               (0x0900000002441FA4)
4XENATIVESTACK               (0x0900000002450DAC)
4XENATIVESTACK               (0x090000000244B02C)
4XENATIVESTACK               (0x09000000026F4E70)
4XENATIVESTACK               (0x090000000244B17C)
4XENATIVESTACK               (0x0900000002450D24)
4XENATIVESTACK               (0x090000000248740C)
4XENATIVESTACK               (0x0000000100007070)
4XENATIVESTACK               (0x090000000054DFEC)
```

The native call stack as seen from the core -
```
(dbx) where
pthread_kill(??, ??) at 0x900000000568884
_p_raise(??) at 0x9000000005680c4
raise.raise(??) at 0x90000000003fbe8
abort() at 0x90000000005e5b8
omrdump_create(??, ??, ??, ??), line 191 in "omrosdump.c"
doSystemDump(??, ??, ??), line 718 in "dmpagent.c"
protectedDumpFunction(??, ??), line 2869 in "dmpagent.c"
omrsig_protect(??, ??, ??, ??, ??, ??, ??), line 384 in "omrsignal.c"
runDumpAgent(??, ??, ??, ??, ??, ??), line 2843 in "dmpagent.c"
triggerDumpAgents(??, ??, ??, ??), line 1028 in "trigger.c"
generateDiagnosticFiles(??, ??), line 1167 in "gphandle.c"
omrsig_protect(??, ??, ??, ??, ??, ??, ??), line 384 in "omrsignal.c"
structuredSignalHandler(??, ??, ??, ??), line 838 in "gphandle.c"
masterSynchSignalHandler(??, ??, ??), line 1001 in "omrsignal.c"
strncpy.strncpy() at 0x900000002a0fbc8
AWT_OnLoad() at 0x9000000072b93c0
sendLifecycleEventCallback(??, ??, ??, ??), line 154 in "vmbootlib.c"
classLoaderRegisterLibrary(??, ??, ??, ??, ??, ??, ??, ??), line 706 in "vmbootlib.c"
IPRA.$openNativeLibrary(??, ??, ??, ??, ??, ??, ??, ??), line 251 in "vmbootlib.c"
registerNativeLibrary(??, ??, ??, ??, ??, ??, ??), line 325 in "vmbootlib.c"
bytecodeLoop() at 0x9000000025b8464
c_cInterpreter(), line 32 in "pcinterp.s"
sendClinit(??, ??), line 419 in "callin.cpp"
initializeImpl(??, ??), line 93 in "ClassInitialization.cpp"
classInitStateMachine(J9VMThread*,J9Class*,J9ClassInitState)(??, ??, ??), line 545 in "ClassInitialization.cpp"
classInitStateMachine(J9VMThread*,J9Class*,J9ClassInitState)(??, ??, ??), line 504 in "ClassInitialization.cpp"
resolveStaticMethodRefInto(??, ??, ??, ??, ??), line 553 in "resolvesupport.cpp"
resolveStaticMethodRef(??, ??, ??, ??), line 588 in "resolvesupport.cpp"
bytecodeLoop() at 0x9000000025a5590
c_cInterpreter(), line 32 in "pcinterp.s"
sendClinit(??, ??), line 419 in "callin.cpp"
initializeImpl(??, ??), line 93 in "ClassInitialization.cpp"
classInitStateMachine(J9VMThread*,J9Class*,J9ClassInitState)(??, ??, ??), line 545 in "ClassInitialization.cpp"
resolveStaticMethodRefInto(??, ??, ??, ??, ??), line 553 in "resolvesupport.cpp"
resolveStaticMethodRef(??, ??, ??, ??), line 588 in "resolvesupport.cpp"
bytecodeLoop() at 0x9000000025a5590
c_cInterpreter(), line 32 in "pcinterp.s"
runCallInMethod(??, ??, ??, ??, ??), line 1073 in "callin.cpp"
gpProtectedRunCallInMethod(void*)(??), line 257 in "jnicsup.cpp"
jniprotect.signalProtectAndRunGlue(??, ??), line 45 in "jniprotect.c"
omrsig_protect(??, ??, ??, ??, ??, ??, ??), line 384 in "omrsignal.c"
jniprotect.gpProtectAndRun(??, ??, ??), line 78 in "jniprotect.c"
gpCheckCallin(??, ??, ??, ??, ??), line 439 in "jnicsup.cpp"
callStaticVoidMethod(0x0, 0x0, 0x122691658, 0x300f8e28, 0x9001000a04a2f50, 0x0, 0x9000000025ca468, 0x667e12cdf), line 293 in "jnicgen.c"
JavaMain() at 0x10000706c
(dbx)
```

I am happy to share additional information if needed.

**Comment by fjeremic** [comment]
@gita-omr FYI in case this is a JIT issue.

**Comment by keithc-ca** [comment]
Could it be that `p` is `NULL` here (there's no `'/'` in buf)?
```
    p = strrchr(buf, '/');
```

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.desktop/unix/native/libawt/awt/awt_LoadLibrary.c#L126

**Comment by gita-omr** [comment]
Does not look like a JIT problem yet.

**Comment by mvdobrinin** [comment]
What @keithc-ca mentioned looks like a valid possibility.

**Comment by mvdobrinin** [comment]
Could it be something along these lines - https://bugs.openjdk.java.net/browse/JDK-8173828?

**Comment by keithc-ca** [comment]
@mvdobrinin With the core file you have, can you look at the locals of the stack frame for `AWT_OnLoad`, specifically the values of `dlinfo.dli_fname` and `buf` and share them here?

**Comment by pshipton** [comment]
@andrew-m-leonard @adamfarley fyi a possible JCL bug here.

**Comment by mvdobrinin** [comment]
Unable to see any local variables on the two methods that would provide the most info. Looks like symbols are missing around these two areas.
```
strncpy.strncpy() at 0x900000002a0fbc8
AWT_OnLoad() at 0x9000000072b93c0
```

**Comment by mvdobrinin** [comment]
I ran it through truss since I wasn't getting anything useful from the core.

```
kload("/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/compressedrefs//tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/compressedrefs/awt", 512, "/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/jli:/tools/java/jdk-11.0.2+9_openj9-0.12.1/../lib::/usr/local/lib:/export/disk1/installers/app/les/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/compressedrefs:/tools/java/jd") Err#2  ENOENT
checkpnt_block(0x0000000000000000, 18)		= 0
thread_tsleep(1, 0x09001000A011D5B0, 0x0000000000000000, 0x0000000000000000) = 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
kload("/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/compressedrefs//tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/compressedrefs/awt", 16843392, "/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/jli:/tools/java/jdk-11.0.2+9_openj9-0.12.1/../lib::/usr/local/lib:/export/disk1/installers/app/les/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/compressedrefs:/tools/java/jd") Err#2  ENOENT
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
thread_tsleep(1, 0x09001000A011D850, 0x0000000000000000, 0x0000000000000000) = 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
kload("/tools/java/jdk-11.0.2+9_openj9-0.12.1/bin/java", 512, "/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/jli:/tools/java/jdk-11.0.2+9_openj9-0.12.1/../lib::/usr/local/lib:/export/disk1/installers/app/les/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/compressedrefs:/tools/java/jd") = 0x08FFFFFFF00000D0
kusla(4, 0x0000000000000000)			= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
thread_tsleep(1, 0x09001000A011D5B0, 0x0000000000000000, 0x0000000000000000) = 0
kload("/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/libawt.so", 512, "/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/jli:/tools/java/jdk-11.0.2+9_openj9-0.12.1/../lib::/usr/local/lib:/export/disk1/installers/app/les/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/compressedrefs:/tools/java/jd") = 0x08FFFFFFF001AC00
thread_tsleep(1, 0x09001000A011D850, 0x0000000000000000, 0x0000000000000000) = 0
kusla(4, 0x0000000000000000)			= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
thread_tsleep(1, 0x09001000A011D5B0, 0x0000000000000000, 0x0000000000000000) = 0
checkpnt_block(0x0000000000000000, 17)		= 0
kload("/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/libawt.so", 16843392, "/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/jli:/tools/java/jdk-11.0.2+9_openj9-0.12.1/../lib::/usr/local/lib:/export/disk1/installers/app/les/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/j9vm:/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/compressedrefs:/tools/java/jd") = 0x08FFFFFFF001AC00
kusla(4, 0x0000000000000000)			= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
thread_twakeup(27656669, 1073741824)		= 0
thread_tsleep(0, 0x09001000A011D5C0, 0x0000000000000000, 0x0000000000000000) = 1073741824
    Received signal #11, SIGSEGV [caught]
__ksetjmp(0x00000001100532D8, 0x0000000000000001, 6, 0x0000000110053528, 0x00000001100535E0, 0x0000000028424406, 0x0000000110058068, 0x0900000000264268) = 0
__ksetjmp(0x00000001100532D8, 0x0000000000000001, 6, 0x0000000110053528, 0x00000001100535E0, 0x0000000028424206, 0x0000000110058068, 0x0900000000264268) = 0
kwrite(2, " U n h a n d l e d   e x".., 63)	= 63
__ksetjmp(0x0000000110052E08, 0x0000000000000001, 6, 0x0000000110053058, 0x0000000110053110, 0x0000000028426206, 0x0000000110058068, 0x0900000000264268) = 0
kwrite(2, " J 9 G e n e r i c _ S i".., 150)	= 150
__ksetjmp(0x0000000110052E08, 0x0000000000000001, 6, 0x0000000110053058, 0x0000000110053110, 0x0000000028426206, 0x0000000110058068, 0x0900000000264268) = 0
kwrite(2, " R 0 = 0 0 0 0 0 0 0 0 0".., 662)	= 662
thread_tsleep(1, 0x09001000A011D5B0, 0x0000000000000000, 0x0000000000000000) = 0
__ksetjmp(0x0000000110052E08, 0x0000000000000001, 6, 0x0000000110053058, 0x0000000110053110, 0x0000000028426206, 0x0000000110058068, 0x0900000000264268) = 0
__ksetjmp(0x0000000110052E08, 0x0000000000000001, 6, 0x0000000110053058, 0x0000000110053110, 0x0000000028426206, 0x0000000110058068, 0x0900000000264268) = 0
kwrite(2, " I A R = 0 9 0 0 0 0 0 0".., 147)	= 147
__ksetjmp(0x0000000110052E08, 0x0000000000000001, 6, 0x0000000110053058, 0x0000000110053110, 0x0000000028426206, 0x0000000110058068, 0x0900000000264268) = 0
kwrite(2, " F P R 0   0 0 0 0 0 0 0".., 1776)	= 1776
__ksetjmp(0x0000000110052E08, 0x0000000000000001, 6, 0x0000000110053058, 0x0000000110053110, 0x0000000028426206, 0x0000000110058068, 0x0900000000264268) = 0
thread_tsleep(1, 0x09001000A011D850, 0x0000000000000000, 0x0000000000000000) = 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
__ksetjmp(0x0000000110052E08, 0x0000000000000001, 6, 0x0000000110053058, 0x0000000110053110, 0x0000000028426206, 0x0000000110058068, 0x0900000000264268) = 0
kwrite(2, " T a r g e t = 2 _ 9 0 _".., 35)	= 35
kwrite(2, " C P U = p p c 6 4   ( 3".., 46)	= 46
__ksetjmp(0x00000001100532D8, 0x0000000000000001, 6, 0x0000000110053528, 0x00000001100535E0, 0x0000000028424206, 0x0000000110058068, 0x0900000000264268) = 0
kwrite(2, " - - - - - - - - - - -  ".., 40)	= 40
__ksetjmp(0x0000000110052968, 0x0000000000000001, 6, 0x0000000110052BB8, 0x0000000110052C70, 0x0000000028424206, 0x0000000110058068, 0x0900000000264268) = 0
__ksetjmp(0x0000000110052968, 0x0000000000000001, 6, 0x0000000110052BB8, 0x0000000110052C70, 0x0000000028424206, 0x0000000110058068, 0x0900000000264268) = 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 17)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
checkpnt_block(0x0000000000000000, 18)		= 0
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
kwrite(2, " ( 0 x 0 0 0 0 0 0 0 1 0".., 21)	= 21
kwrite(2, " ( 0 x 0 9 0 0 0 0 0 0 0".., 21)	= 21
thread_tsleep(1, 0x09001000A011D5B0, 0x0000000000000000, 0x0000000000000000) = 0
kwrite(2, " - - - - - - - - - - - -".., 40)	= 40
statx("/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/java.properties", 0x0000000110051980, 176, 010) = 0
kopen("/tools/java/jdk-11.0.2+9_openj9-0.12.1/lib/java.properties", O_RDONLY|O_LARGEFILE) = 254
kfcntl(254, F_GETFD, 0x0000000000000000)	= 0
kfcntl(254, F_SETFD, 0x0000000000000001)	= 0
kread(254, " # M o n   F e b   0 4  ".., 1023)	= 1023
kread(254, " i r e s   m o d u l e  ".., 1023)	= 1023
kread(254, " s   f o r   c l a s s  ".., 1023)	= 1023
thread_tsleep(1, 0x09001000A011D850, 0x0000000000000000, 0x0000000000000000) = 0
kread(254, " e t h o d   " % 6 $ . *".., 1023)	= 1023
thread_twakeup(27656669, 1073741824)		= 0
thread_tsleep(0, 0x09001000A011D5C0, 0x0000000000000000, 0x0000000000000000) = 1073741824
kread(254, " t i m e   e x t e n s i".., 1023)	= 1023
kread(254, " t i o n s   o n   i d l".., 1023)	= 1023
kread(254, " .\n J 9 V M 1 0 1 = - X".., 1023)	= 1023
kread(254, " n a m e   t h e m .\n J".., 1023)	= 1023
kread(254, " i z e   i s   b i g g e".., 1023)	= 1023
kread(254, " t r o y e d .   U s e  ".., 1023)	= 1023
kread(254, " a b l e   c a c h i n g".., 1023)	= 1023
kread(254, " o f   - X s c s o f t m".., 1023)	= 1023
kread(254, " t h a n   t h e   s h a".., 1023)	= 1023
kread(254, " c e s s '   s u b - o p".., 1023)	= 1023
kread(254, " a s s o c i a t e d   w".., 1023)	= 1023
kread(254, " w r i t e   m u t e x\n".., 1023)	= 1023
kread(254, " o w e d   J I T   d a t".., 1023)	= 1023
kread(254, " \ :   % 4 $ . * 3 $ s  ".., 1023)	= 1023
kread(254, " n f i n d '   i s   s p".., 1023)	= 1023
kread(254, " y   a n d   r e - c r e".., 1023)	= 1023
kread(254, " c l a s s   c a c h e  ".., 1023)	= 1023
kread(254, " s i z e > .\n V E R B 0".., 1023)	= 1023
kread(254, " a s s   c a c h e   f i".., 1023)	= 1023
kread(254, " l a s s - l o a d e r  ".., 1023)	= 1023
thread_tsleep(1, 0x09001000A011D5B0, 0x0000000000000000, 0x0000000000000000) = 0
kread(254, " t h i s   c a c h e\n S".., 1023)	= 1023
kread(254, " t a c k   u s e   w a s".., 1023)	= 1023
kread(254, "     - X X \ : + S t o r".., 1023)	= 1023
kread(254, " i l e d   t o   s t o r".., 1023)	= 1023
kread(254, " n v a l i d   c l a s s".., 1023)	= 1023
kread(254, " . * 3 $ s   A d d r e s".., 1023)	= 1023
kread(254, "                   % * c".., 1023)	= 1023
kread(254, " n   o n e   R u n t i m".., 1023)	= 1023
kread(254, " e r e n c e d   b y   t".., 1023)	= 1023
kread(254, " t r a   b y t e s   a f".., 1023)	= 1023
kread(254, " c o d e   \ =   % 1 $ d".., 1023)	= 1023
kread(254, " c c u r r e d   i n   c".., 1023)	= 1023
kread(254, " e r a t i o n   o f   s".., 1023)	= 1023
kread(254, " a n d   f r a g m e n t".., 1023)	= 1023
kread(254, "   t h e   A O T   m e t".., 1023)	= 1023
kread(254, "   d i a g n o s t i c  ".., 1023)	= 1023
kread(254, " d \ :   F a i l e d   t".., 1023)	= 1023
kread(254, " i o n \ :   % 2 $ . * 1".., 1023)	= 1023
kread(254, " = T h e   " - X X \ : -".., 1023)	= 1023
kread(254, " d e s t r o y   t h e  ".., 1023)	= 1023
kread(254, " a c c e s s i n g   u n".., 1023)	= 1023
kread(254, " s\n S H R C 6 5 6 = T h".., 1023)	= 1023
kread(254, " M P 0 3 6 = I n v a l i".., 1023)	= 1023
kread(254, " e   m e m o r y   f o r".., 1023)	= 1023
kread(254, " h   s h a r e d   c l a".., 1023)	= 1023
kread(254, " t h   s h a r e d   c l".., 1023)	= 1023
close(254)					= 0
kwrite(2, " J V M D U M P 0 3 9 I  ".., 89)	= 89
getuidx(4)					= 206
getuidx(2)					= 206
getuidx(1)					= 206
getgidx(4)					= 203
getgidx(2)					= 203
getgidx(1)					= 203
```

**Comment by keithc-ca** [comment]
Unfortunately, truss doesn't share the information that would be helpful.

Did you get a `javacore` file that you would be willing to share?

Alternatively, we could create a test build that prints some relevant information near the failure point. Would you be willing to test with that?

**Comment by mvdobrinin** [comment]
I would be happy to run a test build if you can provide a package for AIX,

I will also share the javacore privately to keithc@ca.ibm.com.

**Comment by keithc-ca** [comment]
I'd like to have a look at that javacore in case it suggests any adjustments to my anticipated instrumentation.

**Comment by keithc-ca** [comment]
I shared a test build privately with @mvdobrinin.

**Comment by mvdobrinin** [comment]
Running against https://github.com/keithc-ca/openj9-openjdk11/tree/aix, I don't see the issue anymore!

**Comment by keithc-ca** [comment]
Did any of the diagnostics I added fire? In particular, did you see output from this?
```
        fprintf(stderr, "realpath() is not absolute: %s\n", buf);
```

**Comment by mvdobrinin** [comment]
No, I don't see any new output on stdout or stderr.

**Comment by keithc-ca** [comment]
The implementation of `dladdr()` on AIX changed since openj9-0.12.1: you should find that current builds [1] are free from this issue.

[1] https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9#ppc64_aix

**Comment by mvdobrinin** [comment]
Thanks. I can confirm that the current builds fix this as well.
```
>java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.0, JRE 11 AIX ppc64-64-Bit Compressed References 20190418_208 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d
OMR      - 4a4278e
JCL      - 5cc996a based on jdk-11.0.3+7)
```

However, there is strange message logged on the new build. Beyond that my application seems to run fine.
```
loadquery failed (12 Not enough space)
```

**Comment by pshipton** [comment]
Seems the buffer size needs to be increased.

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/84d2599490f3e723429d70013b35ab72cec67495/src/java.desktop/aix/native/libawt/porting_aix.c#L38

**Comment by keithc-ca** [comment]
There's a second copy at [1].  If [2] is a guide, we should perhaps triple that buffer size.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/aix/native/libjli/java_md_aix.c#L30
[2] https://github.com/openssl/openssl/blob/master/crypto/dso/dso_dlfcn.c#L330

**Comment by pshipton** [comment]
@andrew-m-leonard @adamfarley please find somebody to pick up this JCL issue.

**Comment by andrew-m-leonard** [comment]
If I read above correctly it implies the latest openjdk code the issue is fixed...?
"The implementation of dladdr() on AIX changed since openj9-0.12.1: you should find that current builds [1] are free from this issue."

**Comment by pshipton** [comment]
@andrew-m-leonard there is still a problem with the buffer size causing `loadquery failed (12 Not enough space)`. See https://github.com/eclipse/openj9/issues/5530#issuecomment-488522511 and later comments.

**Comment by DanHeidinga** [comment]
@andrew-m-leonard Have you had a chance to look at this further?  It would be good to get this resolved in OpenJDK

**Comment by andrew-m-leonard** [comment]
not yet, I will create a contribution issue for someone to look at

**Comment by andrew-m-leonard** [comment]
https://github.ibm.com/runtimes/openjdk-contribution/issues/844

**Comment by groeges** [comment]
@mvdobrinin Do you have a copy of your test java app that recreates this issue.
I have tried creating a test app using the description you gave on how to recreate and I cant get the failure. If you can provide something that recreates the issue I would be grateful.

**Comment by DanHeidinga** [comment]
There's nothing further for the OpenJ9 project to do here.  Closing this.

**Comment by mvdobrinin** [comment]
@groeges To reproduce this issue, I have to load some native libraries into the JVM (see description above).   The libraries are proprietary so I am unable to share them. The program to reproduce then looks something like this.


```
import java.io.File;
import java.util.Map;
import javax.imageio.ImageIO;
public class Reproduce {
    public static void main(String[] args) {
        try {
            System.loadLibrary("mylib");

            String filePath = "...";
            BufferedImage img = ImageIO.read(new File(filePath));

        }
        catch (Throwable e) {
            System.out.println("Exception : " + e);
            e.printStackTrace();
        }
    }
}
```

**Comment by mvdobrinin** [comment]
Is there an issue I could follow in another Github project to look for a resolution? The changes that @keithc-ca provided did fix my issue, so I think there is something that can be improved here.

**Comment by pshipton** [comment]
@groeges may be able to create a fix that removes the `loadquery failed (12 Not enough space)` message, and contribute it to the OpenJDK project. We don't need this issue to track that. @mvdobrinin If you want to track it via an open issue, you could either open an issue directly at OpenJDK (I think you need to send to the mailing list unless you have permissions to open issues), or what @groeges is doing could be tracked via an issue at https://github.com/ibmruntimes/openj9-openjdk-jdk11 or https://github.com/ibmruntimes/openj9-openjdk-jdk

**Comment by groeges** [comment]
@mvdobrinin I have raised a new issue here https://github.com/ibmruntimes/openj9-openjdk-jdk11/issues/192 in order to track the issue with the error message being displayed and the upstream contribution to OpenJDK. Any issues accessing this issue please let me know.
