### ISSUE TITLE
Missing Java 2 security permissions when using the Attach API

### ISSUE THREAD

**Issue by aguibert** [eclipse/openj9#6119]
Java -version output
--------------------

I don't have `java -version` output, but this is the java version info from the Liberty log header:
```
java.home = /home/jazz_build/_DAkcIIgiEem3a_lXnKb_ZA-EBC.PROD.WASRTC-40H-000-00-00/jbe/jvms/OpenJDK11U-jdk_x64_linux_openj9_11.0.2_9_openj9-0.12.1
java.version = 11.0.2
java.runtime = OpenJDK Runtime Environment (11.0.2+9)
os = Linux (4.4.0-131-generic; amd64) (en_US)
```
As the java.home path implies, this uses JDK 11.0.2+9 using OpenJ9-0.12.1. This is using a released version (not some internal/nightly build).

Summary of problem
------------------

We are using the standard JDK attach API to self-attach to a running VM, but when Java 2 security is enabled, we get a permission error for something that the JDK should be giving itself permission to do (possibly via `$JAVA_HOME/conf/security/java.policy`).

Here is the stack trace:
```
[6/6/19, 12:04:45:092 UTC] 0000001d SystemErr                                                    R java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Unable to get public provider() method
[6/6/19, 12:04:45:098 UTC] 0000001d SystemErr                                                    R 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
[6/6/19, 12:04:45:136 UTC] 0000001d SystemErr                                                    R 	at java.base/java.util.ServiceLoader.findStaticProviderMethod(ServiceLoader.java:617)
[6/6/19, 12:04:45:136 UTC] 0000001d SystemErr                                                    R 	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:877)
[6/6/19, 12:04:45:136 UTC] 0000001d SystemErr                                                    R 	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1076)
[6/6/19, 12:04:45:137 UTC] 0000001d SystemErr                                                    R 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
[6/6/19, 12:04:45:137 UTC] 0000001d SystemErr                                                    R 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
[6/6/19, 12:04:45:138 UTC] 0000001d SystemErr                                                    R 	at com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:258)
[6/6/19, 12:04:45:138 UTC] 0000001d SystemErr                                                    R 	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:200)
[6/6/19, 12:04:45:139 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[6/6/19, 12:04:45:139 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[6/6/19, 12:04:45:139 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[6/6/19, 12:04:45:140 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[6/6/19, 12:04:45:140 UTC] 0000001d SystemErr                                                    R 	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:95)
[6/6/19, 12:04:45:141 UTC] 0000001d SystemErr                                                    R 	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:54)
[6/6/19, 12:04:45:141 UTC] 0000001d SystemErr                                                    R 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
[6/6/19, 12:04:45:141 UTC] 0000001d SystemErr                                                    R 	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.initConnectorAddress(LocalConnectorActivator.java:54)
[6/6/19, 12:04:45:142 UTC] 0000001d SystemErr                                                    R 	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.<clinit>(LocalConnectorActivator.java:44)
[6/6/19, 12:04:45:142 UTC] 0000001d SystemErr                                                    R 	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJmxAddressResource(LocalConnectorActivator.java:196)
[6/6/19, 12:04:45:143 UTC] 0000001d SystemErr                                                    R 	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJMXWorkAreaResource(LocalConnectorActivator.java:188)
[6/6/19, 12:04:45:143 UTC] 0000001d SystemErr                                                    R 	at com.ibm.ws.jmx.connector.local.LocalConnectorActivator.setLocationService(LocalConnectorActivator.java:164)
[6/6/19, 12:04:45:144 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[6/6/19, 12:04:45:144 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[6/6/19, 12:04:45:144 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[6/6/19, 12:04:45:145 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[6/6/19, 12:04:45:145 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
[6/6/19, 12:04:45:145 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
[6/6/19, 12:04:45:146 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
[6/6/19, 12:04:45:146 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
[6/6/19, 12:04:45:147 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.inject.methods.BindMethod.invoke(BindMethod.java:42)
[6/6/19, 12:04:45:147 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1813)
[6/6/19, 12:04:45:148 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.DependencyManager.bindDependency(DependencyManager.java:1637)
[6/6/19, 12:04:45:148 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.DependencyManager.bind(DependencyManager.java:1624)
[6/6/19, 12:04:45:148 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:307)
[6/6/19, 12:04:45:149 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
[6/6/19, 12:04:45:149 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982)
[6/6/19, 12:04:45:150 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
[6/6/19, 12:04:45:150 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765)
[6/6/19, 12:04:45:151 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666)
[6/6/19, 12:04:45:151 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432)
[6/6/19, 12:04:45:151 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665)
[6/6/19, 12:04:45:152 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:338)
[6/6/19, 12:04:45:152 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:382)
[6/6/19, 12:04:45:153 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49)
[6/6/19, 12:04:45:153 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:264)
[6/6/19, 12:04:45:153 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
[6/6/19, 12:04:45:154 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
[6/6/19, 12:04:45:154 UTC] 0000001d SystemErr                                                    R 	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
[6/6/19, 12:04:45:155 UTC] 0000001d SystemErr                                                    R 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
[6/6/19, 12:04:45:155 UTC] 0000001d SystemErr                                                    R 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
[6/6/19, 12:04:45:155 UTC] 0000001d SystemErr                                                    R 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
[6/6/19, 12:04:45:156 UTC] 0000001d SystemErr                                                    R 	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
[6/6/19, 12:04:45:156 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:944)
[6/6/19, 12:04:45:157 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
[6/6/19, 12:04:45:157 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
[6/6/19, 12:04:45:157 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:233)
[6/6/19, 12:04:45:158 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:144)
[6/6/19, 12:04:45:158 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:1)
[6/6/19, 12:04:45:159 UTC] 0000001d SystemErr                                                    R 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
[6/6/19, 12:04:45:159 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:142)
[6/6/19, 12:04:45:160 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:132)
[6/6/19, 12:04:45:160 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:231)
[6/6/19, 12:04:45:160 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.container.Module.publishEvent(Module.java:493)
[6/6/19, 12:04:45:161 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.container.Module.start(Module.java:480)
[6/6/19, 12:04:45:161 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1823)
[6/6/19, 12:04:45:162 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
[6/6/19, 12:04:45:162 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1816)
[6/6/19, 12:04:45:162 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1773)
[6/6/19, 12:04:45:163 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
[6/6/19, 12:04:45:163 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
[6/6/19, 12:04:45:163 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
[6/6/19, 12:04:45:164 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
[6/6/19, 12:04:45:164 UTC] 0000001d SystemErr                                                    R 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)
[6/6/19, 12:04:45:164 UTC] 0000001d SystemErr                                                    R Caused by: 
[6/6/19, 12:04:45:165 UTC] 0000001d SystemErr                                                    R java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.com.ibm.tools.attach.target")
[6/6/19, 12:04:45:165 UTC] 0000001d SystemErr                                                    R 	at java.base/java.security.AccessController.throwACE(AccessController.java:176)
[6/6/19, 12:04:45:166 UTC] 0000001d SystemErr                                                    R 	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:237)
[6/6/19, 12:04:45:166 UTC] 0000001d SystemErr                                                    R 	at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
[6/6/19, 12:04:45:166 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
[6/6/19, 12:04:45:167 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1238)
[6/6/19, 12:04:45:167 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:174)
[6/6/19, 12:04:45:167 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
[6/6/19, 12:04:45:168 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
[6/6/19, 12:04:45:168 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:459)
[6/6/19, 12:04:45:168 UTC] 0000001d SystemErr                                                    R 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[6/6/19, 12:04:45:169 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:978)
[6/6/19, 12:04:45:169 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInSharedClassesCache(BuiltinClassLoader.java:946)
[6/6/19, 12:04:45:169 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:855)
[6/6/19, 12:04:45:169 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:777)
[6/6/19, 12:04:45:170 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:751)
[6/6/19, 12:04:45:170 UTC] 0000001d SystemErr                                                    R 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[6/6/19, 12:04:45:170 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
[6/6/19, 12:04:45:171 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.J9VMInternals.prepareClassImpl(Native Method)
[6/6/19, 12:04:45:171 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.J9VMInternals.prepare(J9VMInternals.java:347)
[6/6/19, 12:04:45:171 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.Class.getMethodHelper(Class.java:1391)
[6/6/19, 12:04:45:172 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.Class.getDeclaredPublicMethods(Class.java:981)
[6/6/19, 12:04:45:172 UTC] 0000001d SystemErr                                                    R 	at java.base/java.lang.Access.getDeclaredPublicMethods(Access.java:289)
[6/6/19, 12:04:45:172 UTC] 0000001d SystemErr                                                    R 	at java.base/java.util.ServiceLoader.findStaticProviderMethod(ServiceLoader.java:615)
[6/6/19, 12:04:45:173 UTC] 0000001d SystemErr                                                    R 	... 70 more
```

Diagnostic files
----------------

here is the default java.policy file that came with my JDK:
```
//
// This system policy file grants a set of default permissions to all domains
// and can be configured to grant additional permissions to modules and other
// code sources. The code source URL scheme for modules linked into a
// run-time image is "jrt".
//
// For example, to grant permission to read the "foo" property to the module
// "com.greetings", the grant entry is:
//
// grant codeBase "jrt:/com.greetings" {
//     permission java.util.PropertyPermission "foo", "read";
// };
//

// default permissions granted to all domains
grant {
    // allows anyone to listen on dynamic ports
    permission java.net.SocketPermission "localhost:0", "listen";

    // "standard" properies that can be read by anyone
    permission java.util.PropertyPermission "java.version", "read";
    permission java.util.PropertyPermission "java.vendor", "read";
    permission java.util.PropertyPermission "java.vendor.url", "read";
    permission java.util.PropertyPermission "java.class.version", "read";
    permission java.util.PropertyPermission "os.name", "read";
    permission java.util.PropertyPermission "os.version", "read";
    permission java.util.PropertyPermission "os.arch", "read";
    permission java.util.PropertyPermission "file.separator", "read";
    permission java.util.PropertyPermission "path.separator", "read";
    permission java.util.PropertyPermission "line.separator", "read";
    permission java.util.PropertyPermission
                   "java.specification.version", "read";
    permission java.util.PropertyPermission "java.specification.vendor", "read";
    permission java.util.PropertyPermission "java.specification.name", "read";
    permission java.util.PropertyPermission
                   "java.vm.specification.version", "read";
    permission java.util.PropertyPermission
                   "java.vm.specification.vendor", "read";
    permission java.util.PropertyPermission
                   "java.vm.specification.name", "read";
    permission java.util.PropertyPermission "java.vm.version", "read";
    permission java.util.PropertyPermission "java.vm.vendor", "read";
    permission java.util.PropertyPermission "java.vm.name", "read";
};
```

**Comment by aguibert** [comment]
This permission is also missing:
```
Permission: 
("com.sun.tools.attach.AttachPermission" "createAttachProvider")
Stack: 
java.security.AccessControlException: Access denied ("com.sun.tools.attach.AttachPermission" "createAttachProvider")java.base/java.security.AccessController.throwACE(AccessController.java:176)
java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:237)
java.base/java.security.AccessController.checkPermission(AccessController.java:373)
java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
com.ibm.ws.kernel.launch.internal.MissingDoPrivDetectionSecurityManager.checkPermission(MissingDoPrivDetectionSecurityManager.java:45)
jdk.attach/com.sun.tools.attach.spi.AttachProvider.<init>(AttachProvider.java:93)
jdk.attach/com.ibm.tools.attach.attacher.OpenJ9AttachProvider.<init>(OpenJ9AttachProvider.java:50)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
java.base/java.util.ServiceLoader$ProviderImpl$2.run(ServiceLoader.java:787)
java.base/java.security.AccessController.doPrivileged(AccessController.java:739)
java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:792)
java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
jdk.attach/com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:260)
jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:200)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:102)
com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper$1.run(LocalConnectorActivator.java:57)
java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.initConnectorAddress(LocalConnectorActivator.java:57)
com.ibm.ws.jmx.connector.local.LocalConnectorActivator$LocalConnectorHelper.<clinit>(LocalConnectorActivator.java:47)
com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJmxAddressResource(LocalConnectorActivator.java:203)
com.ibm.ws.jmx.connector.local.LocalConnectorActivator.createJMXWorkAreaResource(LocalConnectorActivator.java:195)
com.ibm.ws.jmx.connector.local.LocalConnectorActivator.setLocationService(LocalConnectorActivator.java:171)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
org.apache.felix.scr.impl.inject.methods.BindMethod.invoke(BindMethod.java:42)
org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1813)
org.apache.felix.scr.impl.manager.DependencyManager.bindDependency(DependencyManager.java:1637)
org.apache.felix.scr.impl.manager.DependencyManager.bind(DependencyManager.java:1624)
org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:307)
org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982)
org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765)
org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666)
org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432)
org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665)
org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:338)
org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:382)
org.apache.felix.scr.impl.Activator.access$200(Activator.java:49)
org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:264)
org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:944)
org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:233)
org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:144)
org.eclipse.osgi.internal.framework.EquinoxEventPublisher$1.run(EquinoxEventPublisher.java:1)
java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:142)
org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:132)
org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:231)
org.eclipse.osgi.container.Module.publishEvent(Module.java:493)
org.eclipse.osgi.container.Module.start(Module.java:480)
org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1823)
org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1816)
org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1773)
org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)
```

**Comment by pshipton** [comment]
@pdbain-ibm

**Comment by pdbain-ibm** [comment]
I suggest adding `doPrivileged()` to `java.base/com.ibm.tools.attach.target.Attachment.run()`.  @pshipton do you concur?

**Comment by pshipton** [comment]
I don't expect this will fix the first 8 problems reported here. Please confirm the RI behavior as well.

**Comment by pdbain-ibm** [comment]
@aguibert would you kindly provide instructions on reproducing the problem?
Also, would you please test with the reference implementation to confirm that this is OpenJ9-specific?

Thank you

**Comment by pdbain-ibm** [comment]
An attacher running on the reference implementation (`OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28, mixed mode)`) fails if the default security manager is installed:
```
Caused by: java.security.AccessControlException: access denied ("com.sun.tools.attach.AttachPermission" "createAttachProvider")
```

**Comment by aguibert** [comment]
@pdbain-ibm sounds like you were able to reproduce the issue OK?

It sounds like you guys have landed on the end-user needing to grant these perms in their JDK policy file? If so, this seems odd because the code my app is calling is a public Java API and I have already granted full permissions to the code trying to run the attach, and my code invoking the attach is already inside a doPriv. So the root issue here seems that the JDK doesn't trust itself to do something that it's exposing as public API.

**Comment by pdbain-ibm** [comment]
@aguibert 
Have you tested this with the reference implementation (RI) (i.e. HotSpot)?

Note that the example in https://github.com/eclipse/openj9/issues/6119#issuecomment-502819981 was with the RI.

What were your command-line (or other) JVM arguments?

**Comment by pshipton** [comment]
Most of the reported security failures should be fixed by OpenJ9. I expect the user would only have to allow "createAttachProvider" and "attachVirtualMachine".

**Comment by aguibert** [comment]
@pdbain-ibm sorry, I didn't realize you still wanted me to test with the RI since you confirmed there is still an issue in your recent comment. But yes, the same sort of permission issues occur with Hotspot.

My command-line arguments are this:
> /Users/aguibert/dev/java/jdk-11.0.2-hotspot/bin/java -javaagent:/Users/aguibert/dev/git/open-liberty/dev/build.image/wlp/bin/tools/ws-javaagent.jar -Djava.awt.headless=true -Djdk.attach.allowAttachSelf=true --add-exports jdk.management.agent/jdk.internal.agent=ALL-UNNAMED --add-exports java.base/jdk.internal.vm=ALL-UNNAMED --add-exports java.base/sun.security.action=ALL-UNNAMED --add-exports java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-exports jdk.attach/sun.tools.attach=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.naming/javax.naming.spi=ALL-UNNAMED --add-opens java.naming/javax.naming=ALL-UNNAMED --add-opens java.rmi/java.rmi=ALL-UNNAMED --add-opens java.sql/java.sql=ALL-UNNAMED --add-opens java.management/javax.management=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.desktop/java.awt.image=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED -jar /Users/aguibert/dev/git/open-liberty/dev/build.image/wlp/bin/tools/ws-server.jar myServer


@pshipton In this case it is just Liberty code talking directly to a JDK API. Since Liberty controls the JVM launch and Liberty grants all permissions to the Liberty codebases, if Liberty calls this Attach API inside a doPriv, then no permissions should need to be added by the end-user. Is that consistent with your idea of expected behavior too?

**Comment by pshipton** [comment]
@aguibert if it works on the RI, it should work the same for OpenJ9.

> if Liberty calls this Attach API inside a doPriv

This doesn't give any extra permissions, the caller need to have the permissions to start with.

**Comment by aguibert** [comment]
Right, the caller needs permissions, but my point is that the caller _does_ have permissions.

For example, my code can do deep reflection or getting a non-java system property in a do-Priv, but it cannot use this Attach API even inside of a doPriv.

**Comment by JasonFengJ9** [comment]
> Most of the reported security failures should be fixed by OpenJ9. I expect the user would only have to allow "createAttachProvider" and "attachVirtualMachine".

Just echo Pete's https://github.com/eclipse/openj9/issues/6119#issuecomment-503306737, if your code has these two permissions and the call to this attach API `VirtualMachine.attach` within an `AccessController.doPrivileged`, the user of your code (Liberty) doesn't require these permissions.

Note: since modularity era, not all JVM modules have all permissions like `java.base`, so `jdk.attach` might need additional permissions as well.

**Comment by pshipton** [comment]
Thanks for the reminder Jason. Indeed jdk.attach is not a `BOOT_MODULES`.

While lib/security/default.policy doesn't contain any default permissions for jdk.attach, the OpenJ9 implementation is not the same and obviously does require some permissions.

**Comment by JasonFengJ9** [comment]
> `java.security.AccessControlException: Access denied ("com.sun.tools.attach.AttachPermission" "createAttachProvider")` 

This permission is required in custom policy file as well.

**Comment by pdbain-ibm** [comment]
Need (at least) in `default.policy`:
```
grant codeBase "jrt:/jdk.attach" {
    permission java.lang.RuntimePermission "accessClassInPackage.com.ibm.tools.attach.target";
};
```
and need to wrap initialization  of `OpenJ9VirtualMachine`'s timeout fields in `doPrivileged`.

Users would also need to add ` com.sun.tools.attach.AttachPermission "createAttachProvider";`.  Note that this is the case also for the reference implementation.

**Comment by pdbain-ibm** [comment]
[looper.java.txt](https://github.com/eclipse/openj9/files/3315709/looper.java.txt)
[props.java.txt](https://github.com/eclipse/openj9/files/3315710/props.java.txt)

My test case uses the attached files.  Launch the target (`looper`):
```
java looper -q &
```
and test attaching via:
```
java -Djava.security.manager=default props $!
```
My (rough and ready) modifications are at https://github.com/pdbain-ibm/openj9/tree/attach_security

**Comment by JasonFengJ9** [comment]
>     permission java.io.FilePermission "<<ALL FILES>>", "read,write,delete"; permission java.net.SocketPermission "*", "accept,resolve";

These appear too much permissions. Can the code be wrapped by limited doPrivileges and defer the permission granting to the application (Liberty) instead?
`RI` doesn't seem requires these permissions (`createAttachProvider` and `attachVirtualMachine` are needed though). Any justification for `OpenJ9` to request more permissions?

**Comment by pshipton** [comment]
> Can the code be wrapped by limited doPrivileges and defer the permission granting to the application (Liberty) instead?

The application should only have to grant `createAttachProvider` and `attachVirtualMachine`. We could use limited doPrivilege, but I'm not yet convinced this is necessary.

> Any justification for OpenJ9 to request more permissions?

I expect because the implementation is different.

**Comment by pshipton** [comment]
> These appear too much permissions

I don't think it can be more specific since there are system properties that allow the default locations to be modified.

**Comment by aguibert** [comment]
hi @JasonFengJ9, regarding your question on granting `<<ALL FILES>>` file perms, it is because the OpenJ9 attacher creates, reads, and deletes a random temp file like this:
```
"java.io.FilePermission" "/var/folders/pt/bnxxpy3x6jg1nyr86j5qbgfh0000gn/T/.com_ibm_tools_attach" "read,write,delete"
```

**Comment by pshipton** [comment]
Fixed in the head stream by https://github.com/eclipse/openj9/pull/6263
Waiting for a PR for the 0.15 branch before closing this.

**Comment by pshipton** [comment]
Fix for the 0.15 release is https://github.com/eclipse/openj9/pull/6288
