### ISSUE TITLE
Running openj9 on nanoserver fails

### ISSUE THREAD

**Issue by slide** [eclipse/openj9#7725]
Java -version output
--------------------

I can't run `java -version` (this is the problem), here is the binary I am using:
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09_openj9-0.17.0/OpenJDK8U-jdk_x64_windows_openj9_8u232b09_openj9-0.17.0.zip

Summary of problem
------------------

When I create a docker image with Windows nanoserver 1809 and openj9 and try to run a simple `java -version` I get the following error:

```
JVMJ9VM011W Unable to load j9gc29: The specified procedure could not be found.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

My dockerfile is as follows:

```
FROM mcr.microsoft.com/powershell:nanoserver-1809

# $ProgressPreference: https://github.com/PowerShell/PowerShell/issues/2138#issuecomment-251261324
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV JAVA_VERSION jdk8u232-b09_openj9-0.17.0

USER ContainerAdministrator
RUN Write-Host ('Downloading https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09_openj9-0.17.0/OpenJDK8U-jdk_x64_windows_openj9_8u232b09_openj9-0.17.0.zip ...'); \
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
        Invoke-WebRequest -Uri https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09_openj9-0.17.0/OpenJDK8U-jdk_x64_windows_openj9_8u232b09_openj9-0.17.0.zip -O 'openjdk.zip'; \
        Write-Host ('Verifying sha256 (b83053501fcbe69595c2d0919e567c8728b793d7c66ad7bed73f0540894c7397) ...'); \
        if ((Get-FileHash openjdk.zip -Algorithm sha256).Hash -ne 'b83053501fcbe69595c2d0919e567c8728b793d7c66ad7bed73f0540894c7397') { \
                Write-Host 'FAILED!'; \
                exit 1; \
        }; \
        \
        Write-Host 'Expanding Zip ...'; \
        Expand-Archive -Path openjdk.zip -DestinationPath C:\ ; \
        Write-Host 'Removing openjdk.zip ...'; \
        Remove-Item openjdk.zip -Force; \
        $jdkDirectory=(Get-ChildItem -Directory | ForEach-Object { $_.FullName } | Select-String 'jdk'); \
        Move-Item -Path $jdkDirectory C:\openjdk-8;
USER ContainerUser
ENV JAVA_HOME=C:\\openjdk-8 \
ProgramFiles="C:\\Program Files" \
WindowsPATH="C:\\Windows\\system32;C:\\Windows"
ENV PATH="${WindowsPATH};${ProgramFiles}\\PowerShell;${JAVA_HOME}\\bin"
ENV JAVA_TOOL_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle"

```

If I run with `-it` passed to docker run, _sometimes_ I get the following:

```
Unhandled exception
Type=Segmentation error vmState=0xffffffff
Windows_ExceptionCode=c0000139 J9Generic_Signal=00000004 ExceptionAddress=00007FFED310E058 ContextFlags=0010000f
Handler1=00007FFE9FF6C6C0 Handler2=00007FFE9FE4BF50
RDI=0000000001282B98 RSI=00007FFED31887F0 RAX=0000000000000000 RBX=00000000C0000139
RCX=0000000000000048 RDX=0000000000000001 R8=00000000019ED380 R9=00007FFE9FBC2734
R10=0000000000000000 R11=0000C807A27BBEE8 R12=0000000000000003 R13=0000000000000003
R14=0000000000000001 R15=0000000000000003
RIP=00007FFED310E058 RSP=00000000019ECD40 RBP=00000000019ED3E0 GS=002B
FS=0053 ES=002B DS=002B
XMM0 00000000019ed260 (f: 27185760.000000, d: 1.343155e-316)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM2 0057005c00000000 (f: 0.000000, d: 5.117982e-307)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM4 00000000019ed568 (f: 27186536.000000, d: 1.343193e-316)
XMM5 0000000000240024 (f: 2359332.000000, d: 1.165665e-317)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\Windows\SYSTEM32\ntdll.dll
Module_base_address=00007FFED3070000 Offset_in_DLL=000000000009e058
Target=2_90_20191016_492 (Windows Server 2019 10.0 build 17763)
CPU=amd64 (4 logical CPUs) (0x1f9254000 RAM)
JVMDUMP039I Processing dump event "gpf", detail "" at 2019/11/07 16:14:39 - please wait.
JVMDUMP032I JVM requested System dump using 'C:\\core.20191107.161439.40824.0001.dmp' in response to an event
```

When the dump file is done generating (if it generates) I will upload and provide a link.

**Comment by andrewcraik** [comment]
Attn @DanHeidinga @pshipton @dmitripivkine - this is holding up Jenkins adoption.

**Comment by slide** [comment]
It doesn't look like the dump is completing, I left it overnight and it still hasn't completed. Let me know if there is anything I can do to help with reproduction or debug.

**Comment by dmitripivkine** [comment]
Something is missed in Environment. Looks like can not find `j9gc29.dll`. It locates at `${JAVA_HOME}\\bin\\compressedrefs`. Would it find it if added to the `PATH`?

**Comment by slide** [comment]
I don't see a `compressedrefs` in `${JAVA_HOME}\bin`.

```
PS C:\openjdk-8> ls .\bin


    Directory: C:\openjdk-8\bin

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        10/16/2019 10:54 AM          16344 appletviewer.exe
-a----        10/16/2019 10:54 AM          16344 extcheck.exe
-a----        10/16/2019 10:54 AM          16344 idlj.exe
-a----        10/16/2019 10:54 AM          34264 jabswitch.exe
-a----        10/16/2019 10:54 AM          16344 jar.exe
-a----        10/16/2019 10:54 AM          16344 jarsigner.exe
-a----        10/16/2019 10:54 AM         202712 java.exe
-a----        10/16/2019 10:54 AM          16344 javac.exe
-a----        10/16/2019 10:54 AM          16344 javadoc.exe
-a----        10/16/2019 10:54 AM          16344 javah.exe
-a----        10/16/2019 10:54 AM          16344 javap.exe
-a----        10/16/2019 10:54 AM          15832 java-rmi.exe
-a----        10/16/2019 10:54 AM         202712 javaw.exe
-a----        10/16/2019 10:54 AM          16344 jcmd.exe
-a----        10/16/2019 10:54 AM          16856 jconsole.exe
-a----        10/16/2019 10:54 AM          16344 jdb.exe
-a----        10/16/2019 10:54 AM          16344 jdeps.exe
-a----        10/16/2019 10:54 AM          16344 jdmpview.exe
-a----        10/16/2019 10:54 AM          16344 jjs.exe
-a----        10/16/2019 10:55 AM         175064 jli.dll
-a----        10/16/2019 10:54 AM          16344 jmap.exe
-a----        10/16/2019 10:54 AM          16344 jps.exe
-a----        10/16/2019 10:54 AM          16344 jrunscript.exe
-a----        10/16/2019 10:54 AM          16344 jsadebugd.exe
-a----        10/16/2019 10:54 AM          16344 jstack.exe
-a----        10/16/2019 10:54 AM          16344 keytool.exe
-a----        10/16/2019 10:54 AM          16344 kinit.exe
-a----        10/16/2019 10:54 AM          16344 klist.exe
-a----        10/16/2019 10:54 AM          16344 ktab.exe
-a----        10/16/2019 10:55 AM         608216 msvcp100.dll
-a----        10/16/2019 10:55 AM         829400 msvcr100.dll
-a----        10/16/2019 10:54 AM          16344 native2ascii.exe
-a----        10/16/2019 10:54 AM          16344 orbd.exe
-a----        10/16/2019 10:54 AM          16344 pack200.exe
-a----        10/16/2019 10:54 AM          16344 policytool.exe
-a----        10/16/2019 10:54 AM          16344 rmic.exe
-a----        10/16/2019 10:54 AM          16344 rmid.exe
-a----        10/16/2019 10:54 AM          16344 rmiregistry.exe
-a----        10/16/2019 10:54 AM          16344 schemagen.exe
-a----        10/16/2019 10:54 AM          16344 serialver.exe
-a----        10/16/2019 10:54 AM          16344 servertool.exe
-a----        10/16/2019 10:54 AM          16344 tnameserv.exe
-a----        10/16/2019 10:54 AM          16344 traceformat.exe
-a----        10/16/2019 10:54 AM         199128 unpack200.exe
-a----        10/16/2019 10:54 AM          16344 wsgen.exe
-a----        10/16/2019 10:54 AM          16344 wsimport.exe
-a----        10/16/2019 10:54 AM          16344 xjc.exe
```

**Comment by dmitripivkine** [comment]
Sorry, I missed that this is Java 8. Please check `${JAVA_HOME}\\jre\\bin\\compressedrefs`

**Comment by slide** [comment]
I now only get the exception. You can see that I added `${JAVA_HOME}\jre\bin\compressedrefs` to the PATH

```
PS C:\> Write-Host $env:PATH
C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell;C:\openjdk-8\bin;C:\openjdk-8\jre\bin\compressedrefs
PS C:\> java -version
Unhandled exception
Type=Segmentation error vmState=0xffffffff
Windows_ExceptionCode=c0000139 J9Generic_Signal=00000004 ExceptionAddress=00007FFED310E058 ContextFlags=0010000f
Handler1=00007FFE9C34C6C0 Handler2=00007FFE9CB8BF50
RDI=0000000000FE3E98 RSI=00007FFED31887F0 RAX=0000000000000000 RBX=00000000C0000139
RCX=0000000000000048 RDX=0000000000000001 R8=00000000014ED340 R9=00007FFE9CD52734
R10=0000000000000000 R11=00007F3D6578275F R12=0000000000000003 R13=0000000000000003
R14=0000000000000001 R15=0000000000000003
RIP=00007FFED310E058 RSP=00000000014ECD00 RBP=00000000014ED3A0 GS=002B
FS=0053 ES=002B DS=002B
XMM0 00000000014ed220 (f: 21942816.000000, d: 1.084119e-316)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM2 0057005c00000000 (f: 0.000000, d: 5.117982e-307)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM4 00000000014ed528 (f: 21943592.000000, d: 1.084157e-316)
XMM5 0000000000240024 (f: 2359332.000000, d: 1.165665e-317)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\Windows\SYSTEM32\ntdll.dll
Module_base_address=00007FFED3070000 Offset_in_DLL=000000000009e058
Target=2_90_20191016_492 (Windows Server 2019 10.0 build 17763)
CPU=amd64 (4 logical CPUs) (0x1f9254000 RAM)
JVMDUMP039I Processing dump event "gpf", detail "" at 2019/11/08 08:29:28 - please wait.
JVMDUMP032I JVM requested System dump using 'C:\\core.20191108.082928.66588.0001.dmp' in response to an event
```

**Comment by dsouzai** [comment]
This looks like the same symptom as https://github.com/eclipse/openj9/issues/3747 except it's happening on java 8 now.

**Comment by slide** [comment]
So, the nanoserver image may not have a DLL that is needed. I will try and determine what DLL is missing.

**Comment by DanHeidinga** [comment]
Depending on how far the VM has started before the crash, we might be able to get more diagnostics about what dlls are being loaded / how far we got by adding `-verbose:init` to the java commandline

**Comment by dmitripivkine** [comment]
I would add `${JAVA_HOME}\\jre\\bin` to PATH as well. Looks like Java Launcher is confused somehow and can not locate subfolders properly

**Comment by slide** [comment]
I tried adding `${JAVA_HOME}\jre\bin' to the PATH, the exception remains. Adding `-verbose:init` did not add any additional log output.

**Comment by dmitripivkine** [comment]
I tried to google problem and found https://github.com/AdoptOpenJDK/openjdk-installer/issues/58
That problem has been fixed obviously but here we have the same kind of failure

**Comment by slide** [comment]
I haven't installed the hotpot jvm at all on this system, so I don't think its the same issue.

**Comment by pshipton** [comment]
I was able to recreate this. With ` -verbose:init` a working JVM shows
```
Checking results for stage ALL_DEFAULT_LIBRARIES_LOADED

Loading libraries at load stage LOAD_BY_DEFAULT:
        Loaded library j9jit29
                completed with rc=1 in 1333965 nano sec.
        Loaded library j9gc29
                completed with rc=1 in 499918 nano sec.
        Loaded library j9vrb29
                completed with rc=1 in 357212 nano sec.
        Loaded library j9shr29
                completed with rc=1 in 340005 nano sec.
        Loaded library j9jvmti29
                completed with rc=1 in 316845 nano sec.
        Loaded library jclse29
                completed with rc=1 in 364471 nano sec.
```

In the docker container we get the following, which seems to indicate the problem is still in loading j9gc29.dll
```
Checking results for stage ALL_DEFAULT_LIBRARIES_LOADED

Loading libraries at load stage LOAD_BY_DEFAULT:
        Loaded library j9jit29
                completed with rc=1 in 6963500 nano sec.
Unhandled exception
Type=Segmentation error vmState=0xffffffff
...
```

**Comment by pshipton** [comment]
Note `-Xint` doesn't change the behavior except the j9jit29 isn't loaded.

Looking at the imports of j9gc29.dll, ignoring things included with the JVM it requires
MSVCR100.dll
WINMM.dll
KERNEL32.dll

I think WINMM.dll is missing from the container, I don't find it.

**Comment by slide** [comment]
MSVCR100.dll and MSVCP100.dll are also not in the container.

**Comment by slide** [comment]
WINMM.dll is in C:\Windows\System32\Forwarders, I am not sure how that directory is supposed to work

**Comment by slide** [comment]
I'm downloading this tool to see if it will help understand what might be missing: https://blogs.technet.microsoft.com/nanoserver/2016/04/27/nanoserverapiscan-exe-updated-for-tp5/

**Comment by slide** [comment]
Nothing shows up for `${JAVA_HOME}\bin', but there are several issues for items in `${JAVA_HOME}\jre\bin`

```
-----------------------------------------------------------------------------
=== awt.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\awt.dll ===


-----------------------------------------------------------------------------
=== dt_shmem.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\dt_shmem.dll ===


-----------------------------------------------------------------------------
=== dt_socket.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\dt_socket.dll ===


-----------------------------------------------------------------------------
=== fontmanager.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\fontmanager.dll ===


-----------------------------------------------------------------------------
=== freetype.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\freetype.dll ===


-----------------------------------------------------------------------------
=== hprof.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\hprof.dll ===

ERRORS:

  WSOCK32.dll
    14(Proc not found)
    15(Proc not found)
    8(Proc not found)
    115(Proc not found)
    116(Proc not found)
    19(Proc not found)
    22(Proc not found)
    16(Proc not found)
    52(Proc not found)
    9(Proc not found)
    23(Proc not found)
    4(Proc not found)
    3(Proc not found)

-----------------------------------------------------------------------------
=== instrument.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\instrument.dll ===


-----------------------------------------------------------------------------
=== j2pcsc.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\j2pcsc.dll ===

ERRORS:

  WinSCard.dll
    SCardControl(Proc not found)
    SCardEndTransaction(Proc not found)
    SCardBeginTransaction(Proc not found)
    SCardGetStatusChangeA(Proc not found)
    SCardDisconnect(Proc not found)
    SCardStatusA(Proc not found)
    SCardTransmit(Proc not found)
    SCardConnectA(Proc not found)
    SCardListReadersA(Proc not found)
    SCardEstablishContext(Proc not found)

-----------------------------------------------------------------------------
=== j2pkcs11.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\j2pkcs11.dll ===


-----------------------------------------------------------------------------
=== jaas_nt.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jaas_nt.dll ===


-----------------------------------------------------------------------------
=== jabswitch.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jabswitch.exe ===


-----------------------------------------------------------------------------
=== java-rmi.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\java-rmi.exe ===


-----------------------------------------------------------------------------
=== java.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\java.dll ===


-----------------------------------------------------------------------------
=== java.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\java.exe ===


-----------------------------------------------------------------------------
=== JavaAccessBridge-64.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\JavaAccessBridge-64.dll ===


-----------------------------------------------------------------------------
=== javaw.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\javaw.exe ===


-----------------------------------------------------------------------------
=== java_crw_demo.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\java_crw_demo.dll ===


-----------------------------------------------------------------------------
=== jawt.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jawt.dll ===


-----------------------------------------------------------------------------
=== JAWTAccessBridge-64.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\JAWTAccessBridge-64.dll ===


-----------------------------------------------------------------------------
=== jdwp.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jdwp.dll ===


-----------------------------------------------------------------------------
=== jjs.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jjs.exe ===


-----------------------------------------------------------------------------
=== jli.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jli.dll ===


-----------------------------------------------------------------------------
=== jncrypto.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jncrypto.dll ===


-----------------------------------------------------------------------------
=== jpeg.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jpeg.dll ===


-----------------------------------------------------------------------------
=== jsdt.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jsdt.dll ===


-----------------------------------------------------------------------------
=== jsig.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jsig.dll ===


-----------------------------------------------------------------------------
=== jsound.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jsound.dll ===

ERRORS:

  WINMM.dll
    mixerOpen(Proc not found)
    mixerSetControlDetails(Proc not found)
    mixerGetControlDetailsA(Proc not found)
    mixerClose(Proc not found)
    mixerGetDevCapsA(Proc not found)
    mixerGetLineControlsA(Proc not found)
    mixerGetLineInfoA(Proc not found)
    mixerGetNumDevs(Proc not found)
    midiOutPrepareHeader(Proc not found)
    midiOutLongMsg(Proc not found)
    midiOutReset(Proc not found)
    midiOutClose(Proc not found)
    midiOutOpen(Proc not found)
    midiOutShortMsg(Proc not found)
    midiOutUnprepareHeader(Proc not found)
    midiOutGetDevCapsA(Proc not found)
    midiOutGetNumDevs(Proc not found)
    midiOutGetErrorTextA(Proc not found)
    midiInStop(Proc not found)
    midiInStart(Proc not found)
    midiInReset(Proc not found)
    midiInClose(Proc not found)
    midiInUnprepareHeader(Proc not found)
    midiInPrepareHeader(Proc not found)
    midiInGetDevCapsA(Proc not found)
    midiInGetNumDevs(Proc not found)
    midiInGetErrorTextA(Proc not found)
    midiInOpen(Proc not found)
    midiInAddBuffer(Proc not found)

-----------------------------------------------------------------------------
=== jsoundds.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\jsoundds.dll ===

ERRORS:

  DSOUND.dll
    2(Proc not found)
    6(Proc not found)
    1(Proc not found)
    7(Proc not found)

-----------------------------------------------------------------------------
=== keytool.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\keytool.exe ===


-----------------------------------------------------------------------------
=== kinit.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\kinit.exe ===


-----------------------------------------------------------------------------
=== klist.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\klist.exe ===


-----------------------------------------------------------------------------
=== ktab.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\ktab.exe ===


-----------------------------------------------------------------------------
=== lcms.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\lcms.dll ===


-----------------------------------------------------------------------------
=== libcrypto-1_1-x64.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\libcrypto-1_1-x64.dll ===

ERRORS:

  MSVCR120.dll
    __crtUnhandledException(Proc not found)
    __crtTerminateProcess(Proc not found)
    __crtCaptureCurrentContext(Proc not found)
    __crtCapturePreviousContext(Proc not found)

-----------------------------------------------------------------------------
=== management.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\management.dll ===


-----------------------------------------------------------------------------
=== mlib_image.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\mlib_image.dll ===


-----------------------------------------------------------------------------
=== msvcp100.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\msvcp100.dll ===


-----------------------------------------------------------------------------
=== msvcr100.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\msvcr100.dll ===


-----------------------------------------------------------------------------
=== net.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\net.dll ===


-----------------------------------------------------------------------------
=== nio.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\nio.dll ===


-----------------------------------------------------------------------------
=== npt.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\npt.dll ===


-----------------------------------------------------------------------------
=== orbd.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\orbd.exe ===


-----------------------------------------------------------------------------
=== pack200.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\pack200.exe ===


-----------------------------------------------------------------------------
=== policytool.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\policytool.exe ===


-----------------------------------------------------------------------------
=== rmid.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\rmid.exe ===


-----------------------------------------------------------------------------
=== rmiregistry.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\rmiregistry.exe ===


-----------------------------------------------------------------------------
=== servertool.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\servertool.exe ===


-----------------------------------------------------------------------------
=== splashscreen.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\splashscreen.dll ===


-----------------------------------------------------------------------------
=== sunec.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\sunec.dll ===


-----------------------------------------------------------------------------
=== sunmscapi.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\sunmscapi.dll ===


-----------------------------------------------------------------------------
=== tnameserv.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\tnameserv.exe ===


-----------------------------------------------------------------------------
=== unpack.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\unpack.dll ===


-----------------------------------------------------------------------------
=== unpack200.exe ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\unpack200.exe ===


-----------------------------------------------------------------------------
=== verify.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\verify.dll ===


-----------------------------------------------------------------------------
=== w2k_lsa_auth.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\w2k_lsa_auth.dll ===

ERRORS:

  WSOCK32.dll
    8(Proc not found)

-----------------------------------------------------------------------------
=== WindowsAccessBridge-64.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\WindowsAccessBridge-64.dll ===


-----------------------------------------------------------------------------
=== zip.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\zip.dll ===


-----------------------------------------------------------------------------
=== cuda4j29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\cuda4j29.dll ===


-----------------------------------------------------------------------------
=== j9dmp29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9dmp29.dll ===


-----------------------------------------------------------------------------
=== j9gc29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9gc29.dll ===

ERRORS:

  WINMM.dll
    timeSetEvent(Proc not found)
    timeKillEvent(Proc not found)

-----------------------------------------------------------------------------
=== j9gcchk29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9gcchk29.dll ===


-----------------------------------------------------------------------------
=== j9hookable29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9hookable29.dll ===


-----------------------------------------------------------------------------
=== j9jextract.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9jextract.dll ===


-----------------------------------------------------------------------------
=== j9jit29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9jit29.dll ===


-----------------------------------------------------------------------------
=== j9jnichk29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9jnichk29.dll ===


-----------------------------------------------------------------------------
=== j9jvmti29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9jvmti29.dll ===


-----------------------------------------------------------------------------
=== j9prt29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9prt29.dll ===


-----------------------------------------------------------------------------
=== j9shr29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9shr29.dll ===


-----------------------------------------------------------------------------
=== j9thr29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9thr29.dll ===


-----------------------------------------------------------------------------
=== j9trc29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9trc29.dll ===


-----------------------------------------------------------------------------
=== j9vm29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9vm29.dll ===


-----------------------------------------------------------------------------
=== j9vmchk29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9vmchk29.dll ===


-----------------------------------------------------------------------------
=== j9vrb29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9vrb29.dll ===


-----------------------------------------------------------------------------
=== j9zlib29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\j9zlib29.dll ===


-----------------------------------------------------------------------------
=== jclse29.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\jclse29.dll ===


-----------------------------------------------------------------------------
=== jvm.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\jvm.dll ===


-----------------------------------------------------------------------------
=== management.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\management.dll ===


-----------------------------------------------------------------------------
=== management_ext.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\management_ext.dll ===


-----------------------------------------------------------------------------
=== omrsig.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\compressedrefs\omrsig.dll ===


-----------------------------------------------------------------------------
=== jsig.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\j9vm\jsig.dll ===


-----------------------------------------------------------------------------
=== jvm.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\j9vm\jvm.dll ===


-----------------------------------------------------------------------------
=== jsig.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\server\jsig.dll ===


-----------------------------------------------------------------------------
=== jvm.dll ===
=== C:\Users\acearl\Downloads\NanoServerApiScan\jdk8u232-b09\jre\bin\server\jvm.dll ===
```

**Comment by slide** [comment]
For the winmm.dll functions, the timerSetEvent is obsolete according to this doc: https://docs.microsoft.com/en-us/previous-versions/dd757634(v%3Dvs.85).

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/blob/3c98e634d4af0013bedd9a7a88e79b01eaf6b4d7/runtime/gc_realtime/MetronomeAlarm.cpp#L221

https://github.com/eclipse/openj9/blob/3c98e634d4af0013bedd9a7a88e79b01eaf6b4d7/runtime/gc_realtime/MetronomeAlarm.cpp#L302

**Comment by pshipton** [comment]
> MSVCR100.dll and MSVCP100.dll are also not in the container.

Note these are included with the JVM in `jre/bin`.

However MSVCR120.dll used by libcrypto-1_1-x64.dll is not. libcrypto-1_1-x64.dll (openssl) is used for crypto acceleration, https://www.eclipse.org/openj9/docs/djdknativecrypto/

**Comment by slide** [comment]
I removed that comment because I found them in the jre/bin directory. I'll try copying MSCVR120.dll into the image and see if it helps.

**Comment by slide** [comment]
I did a Get-ChildItem in C:\Windows\System32 in my Dockerfile and see this:

```
-a----         10/2/2019  5:13 AM         660032 msvcp120.dll
-a----         10/2/2019  5:13 AM         946712 msvcr120.dll
```

So, that runtime IS there.

**Comment by pshipton** [comment]
The current failure to start appears to be related to j9gc29.so. I'll hack out the missing APIs and build a new runtime we can try.

**Comment by slide** [comment]
Did you just add `-verbose:init' to `java -version` or do you have to do something different?

**Comment by pshipton** [comment]
I put it before the `-version`, it doesn't work if you put it after. I also tried including `-Xdump:none` to avoid creating the core file, not that it helps because it just hangs anyway.

**Comment by pshipton** [comment]
My build with timeSetEvent() and timeKillEvent() removed is https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/427. There will be a link to the JVM when it's done. These APIs are used by the metronome GC, which isn't the default, so it won't cause any problems until you run with `-Xgcpolicy:metronome`.

**Comment by pshipton** [comment]
grr, there is a mismatch between the OpenJ9 and OMR projects atm. Should be resolved in a few hours, but I'll try to work around it.
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/428

**Comment by pshipton** [comment]
third time lucky? https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/429

**Comment by pshipton** [comment]
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_windows_Personal/429/OpenJ9-JDK8-x86-64_windows-20191108-213308.tar.gz

**Comment by slide** [comment]
With this build, `java -verbose:init -version` gives the following output:

```
PS C:\> java -verbose:init -version
Parsing environment variable JAVA_TOOL_OPTIONS
Adding command line arguments
VM known paths  - j9libvm directory: C:\openjdk-8\jre\lib\compressedrefs
                - j2seRoot directory: C:\openjdk-8\jre\bin\compressedrefs
Option 0 optionString="-Xoptionsfile=C:\openjdk-8\jre\bin\compressedrefs\options.default" extraInfo=0000000000000000 from environment variable ="N/A"
Option 1 optionString="-Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry
,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/Construct
orHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLoc
kword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/l
ang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/St
aticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,no
Lockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple" extraInfo=0000
000000000000 from environment variable ="N/A"
Option 2 optionString="-Xjcl:jclse29" extraInfo=0000000000000000 from environment variable ="N/A"
Option 3 optionString="-Dcom.ibm.oti.vm.bootstrap.library.path=C:\openjdk-8\jre\bin\compressedrefs;C:\openjdk-8\jre\bin" extraInfo=0000000000000000 from environment variable ="N/A"
Option 4 optionString="-Dsun.boot.library.path=C:\openjdk-8\jre\bin\compressedrefs;C:\openjdk-8\jre\bin" extraInfo=0000000000000000 from environment variable ="N/A"
Option 5 optionString="-Djava.library.path=C:\openjdk-8\jre\bin\compressedrefs;C:\openjdk-8\jre\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell;C:\open
jdk-8\bin;C:\openjdk-8\jre\bin;C:\openjdk-8\jre\bin\compressedrefs;." extraInfo=0000000000000000 from environment variable ="N/A"
Option 6 optionString="-Djava.home=C:\openjdk-8\jre" extraInfo=0000000000000000 from environment variable ="N/A"
Option 7 optionString="-Djava.ext.dirs=C:\openjdk-8\jre\lib\ext" extraInfo=0000000000000000 from environment variable ="N/A"
Option 8 optionString="-Duser.dir=C:\" extraInfo=0000000000000000 from environment variable ="N/A"
Option 9 optionString="-XX:+IgnoreUnrecognizedVMOptions" extraInfo=0000000000000000 from environment variable ="N/A"
Option 10 optionString="-XX:+UseContainerSupport" extraInfo=0000000000000000 from environment variable ="N/A"
Option 11 optionString="-XX:+IdleTuningCompactOnIdle" extraInfo=0000000000000000 from environment variable ="N/A"
Option 12 optionString="-XX:+IdleTuningGcOnIdle" extraInfo=0000000000000000 from environment variable ="N/A"
Option 13 optionString="-Djava.class.path=." extraInfo=0000000000000000 from environment variable ="N/A"
Option 14 optionString="-verbose:init" extraInfo=0000000000000000 from environment variable ="N/A"
Option 15 optionString="-Dsun.java.launcher=SUN_STANDARD" extraInfo=0000000000000000 from environment variable ="N/A"

Initializing DLL load table:
Creating table entry for j9jit29
Creating table entry for j9jitd29
Creating table entry for j9bcv29
Creating table entry for j9gc29
Creating table entry for j9dyn29
Creating table entry for j9vrb29
Creating table entry for j9dmp29
Creating table entry for j9trc29
Creating table entry for j9jnichk29
Creating table entry for j9vmchk29
Creating table entry for j9shr29
Creating table entry for j9jvmti29
Creating table entry for j9gcchk29
Creating table entry for j9dbg29
Creating table entry for jclse29
Creating table entry for zeroInitStages
Creating table entry for VMInitStages
Creating table entry for threadInitStages

Customizing DLL load table:
JVMTI required... whacking table
JIT required... whacking table
verbose support required... whacking table
verbose support required in j2se... whacking table
verbose support required... whacking table
shared classes support required... whacking table
Dump support required... whacking table

Loading libraries at load stage EARLY_LOAD:
        Loaded library j9dmp29
                completed with rc=1 in 784300 nano sec.
        Loaded library j9trc29
                completed with rc=1 in 404500 nano sec.

Checking results for stage LOAD_STAGE

Running initialization stage PORT_LIBRARY_GUARANTEED
        for library j9bcv29...
                completed with rc=0 in 70100 nano sec.
        for library j9dyn29...
                completed with rc=0 in 8500 nano sec.
        for library j9dmp29...
                completed with rc=0 in 836700 nano sec.
        for library j9trc29...
                completed with rc=0 in 19000 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 700 nano sec.
        for library VMInitStages...
                completed with rc=0 in 34600 nano sec.
        for library threadInitStages...
                completed with rc=0 in 1000 nano sec.

Checking results for stage PORT_LIBRARY_GUARANTEED

Running initialization stage ALL_DEFAULT_LIBRARIES_LOADED
        for library j9bcv29...
                completed with rc=0 in 400 nano sec.
        for library j9dyn29...
                completed with rc=0 in 200 nano sec.
        for library j9dmp29...
                completed with rc=0 in 200 nano sec.
        for library j9trc29...
                completed with rc=0 in 300 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 200 nano sec.
        for library VMInitStages...
                completed with rc=0 in 27300 nano sec.
        for library threadInitStages...
                completed with rc=0 in 100 nano sec.

Checking results for stage ALL_DEFAULT_LIBRARIES_LOADED

Loading libraries at load stage LOAD_BY_DEFAULT:
        Loaded library j9jit29
                completed with rc=1 in 370200 nano sec.
        Loaded library j9gc29
                completed with rc=1 in 711400 nano sec.
        Loaded library j9vrb29
                completed with rc=1 in 197500 nano sec.
        Loaded library j9shr29
                completed with rc=1 in 203200 nano sec.
        Loaded library j9jvmti29
                completed with rc=1 in 178200 nano sec.
        Loaded library jclse29
                completed with rc=1 in 239800 nano sec.

Checking results for stage LOAD_STAGE

Running initialization stage ALL_LIBRARIES_LOADED
        for library j9jit29...
                completed with rc=0 in 4700 nano sec.
        for library j9bcv29...
                completed with rc=0 in 400 nano sec.
        for library j9gc29...
                completed with rc=0 in 2924000 nano sec.
        for library j9dyn29...
                completed with rc=0 in 400 nano sec.
        for library j9vrb29...
                completed with rc=0 in 2900 nano sec.
        for library j9dmp29...
                completed with rc=0 in 1100 nano sec.
        for library j9trc29...
                completed with rc=0 in 1300 nano sec.
        for library j9shr29...
                completed with rc=0 in 25800 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 6100 nano sec.
        for library jclse29...
                completed with rc=0 in 387100 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 400 nano sec.
        for library VMInitStages...

Detecting agent Xruns...
                completed with rc=0 in 138300 nano sec.
        for library threadInitStages...
                completed with rc=0 in 300 nano sec.

Checking results for stage ALL_LIBRARIES_LOADED

Loading libraries at load stage FORCE_LATE_LOAD:

Checking results for stage LOAD_STAGE

Running initialization stage DLL_LOAD_TABLE_FINALIZED
        for library j9jit29...
                completed with rc=0 in 48400 nano sec.
        for library j9bcv29...
                completed with rc=0 in 500 nano sec.
        for library j9gc29...
                completed with rc=0 in 500 nano sec.
        for library j9dyn29...
                completed with rc=0 in 200 nano sec.
        for library j9vrb29...
                completed with rc=0 in 32700 nano sec.
        for library j9dmp29...
                completed with rc=0 in 300 nano sec.
        for library j9trc29...
                completed with rc=0 in 700 nano sec.
        for library j9shr29...
                completed with rc=0 in 1200 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 400 nano sec.
        for library jclse29...
                completed with rc=0 in 100 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 100 nano sec.
        for library VMInitStages...
                completed with rc=0 in 100 nano sec.
        for library threadInitStages...
                completed with rc=0 in 100 nano sec.

Checking results for stage DLL_LOAD_TABLE_FINALIZED

Running shutdown stage LIBRARIES_ONUNLOAD...

Checking results for stage LIBRARIES_ONUNLOAD

Forcing unload of libraries...

Checking results for stage UNLOAD_STAGE

Running initialization stage VM_THREADING_INITIALIZED
        for library j9jit29...
                completed with rc=0 in 700 nano sec.
        for library j9bcv29...
                completed with rc=0 in 200 nano sec.
        for library j9gc29...
                completed with rc=0 in 700 nano sec.
        for library j9dyn29...
                completed with rc=0 in 100 nano sec.
        for library j9vrb29...
                completed with rc=0 in 300 nano sec.
        for library j9dmp29...
                completed with rc=0 in 200 nano sec.
        for library j9trc29...
                completed with rc=0 in 300 nano sec.
        for library j9shr29...
                completed with rc=0 in 300 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 300 nano sec.
        for library jclse29...
                completed with rc=0 in 100 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 100 nano sec.
        for library VMInitStages...
                completed with rc=0 in 100 nano sec.
        for library threadInitStages...
                completed with rc=0 in 62400 nano sec.

Checking results for stage VM_THREADING_INITIALIZED

Running initialization stage HEAP_STRUCTURES_INITIALIZED
        for library j9jit29...
                completed with rc=0 in 500 nano sec.
        for library j9bcv29...
                completed with rc=0 in 200 nano sec.
        for library j9gc29...
                completed with rc=0 in 625300 nano sec.
        for library j9dyn29...
                completed with rc=0 in 100 nano sec.
        for library j9vrb29...
                completed with rc=0 in 200 nano sec.
        for library j9dmp29...
                completed with rc=0 in 200 nano sec.
        for library j9trc29...
                completed with rc=0 in 300 nano sec.
        for library j9shr29...
                completed with rc=0 in 400 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 600 nano sec.
        for library jclse29...
                completed with rc=0 in 100 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 100 nano sec.
        for library VMInitStages...
                completed with rc=0 in 20300 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage HEAP_STRUCTURES_INITIALIZED

Running initialization stage ALL_VM_ARGS_CONSUMED
        for library j9jit29...
                completed with rc=0 in 2600 nano sec.
        for library j9bcv29...
                completed with rc=0 in 10800 nano sec.
        for library j9gc29...
                completed with rc=0 in 900 nano sec.
        for library j9dyn29...
                completed with rc=0 in 300 nano sec.
        for library j9vrb29...
                completed with rc=0 in 700 nano sec.
        for library j9dmp29...
                completed with rc=0 in 200 nano sec.
        for library j9trc29...
                completed with rc=0 in 500 nano sec.
        for library j9shr29...
                completed with rc=0 in 1900 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 40400 nano sec.
        for library jclse29...
                completed with rc=0 in 1200 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 300 nano sec.
        for library VMInitStages...
                enabled network query to determine host name and IP address for RAS.
                completed with rc=0 in 3236400 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage ALL_VM_ARGS_CONSUMED

Running initialization stage BYTECODE_TABLE_SET
        for library j9jit29...
                completed with rc=0 in 1800 nano sec.
        for library j9bcv29...
                completed with rc=0 in 55000 nano sec.
        for library j9gc29...
                completed with rc=0 in 1500 nano sec.
        for library j9dyn29...
                completed with rc=0 in 20700 nano sec.
        for library j9vrb29...
                completed with rc=0 in 2200 nano sec.
        for library j9dmp29...
                completed with rc=0 in 900 nano sec.
        for library j9trc29...
                completed with rc=0 in 1400 nano sec.
        for library j9shr29...
                completed with rc=0 in 1500 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 900 nano sec.
        for library jclse29...
                completed with rc=0 in 700 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 500 nano sec.
        for library VMInitStages...
                completed with rc=0 in 800 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage BYTECODE_TABLE_SET

Running initialization stage SYSTEM_CLASSLOADER_SET
        for library j9jit29...
                completed with rc=0 in 1700 nano sec.
        for library j9bcv29...
                completed with rc=0 in 300 nano sec.
        for library j9gc29...
                completed with rc=0 in 700 nano sec.
        for library j9dyn29...
                completed with rc=0 in 500 nano sec.
        for library j9vrb29...
                completed with rc=0 in 600 nano sec.
        for library j9dmp29...
                completed with rc=0 in 200 nano sec.
        for library j9trc29...
                completed with rc=0 in 1000 nano sec.
        for library j9shr29...
                completed with rc=0 in 18900 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 3100 nano sec.
        for library jclse29...
                completed with rc=0 in 1800 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 1700 nano sec.
        for library VMInitStages...
                completed with rc=0 in 36000 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage SYSTEM_CLASSLOADER_SET

Running initialization stage DEBUG_SERVER_INITIALIZED
        for library j9jit29...
                completed with rc=0 in 1500 nano sec.
        for library j9bcv29...
                completed with rc=0 in 400 nano sec.
        for library j9gc29...
                completed with rc=0 in 900 nano sec.
        for library j9dyn29...
                completed with rc=0 in 400 nano sec.
        for library j9vrb29...
                completed with rc=0 in 1000 nano sec.
        for library j9dmp29...
                completed with rc=0 in 300 nano sec.
        for library j9trc29...
                completed with rc=0 in 600 nano sec.
        for library j9shr29...
                completed with rc=0 in 700 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 500 nano sec.
        for library jclse29...
                completed with rc=0 in 300 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 200 nano sec.
        for library VMInitStages...
                completed with rc=0 in 200 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage DEBUG_SERVER_INITIALIZED

Running initialization stage TRACE_ENGINE_INITIALIZED
        for library j9jit29...
                completed with rc=0 in 800 nano sec.
        for library j9bcv29...
                completed with rc=0 in 200 nano sec.
        for library j9gc29...
                completed with rc=0 in 800 nano sec.
        for library j9dyn29...
                completed with rc=0 in 200 nano sec.
        for library j9vrb29...
                completed with rc=0 in 300 nano sec.
        for library j9dmp29...
                completed with rc=0 in 24000 nano sec.
        for library j9trc29...
                completed with rc=0 in 1061700 nano sec.
        for library j9shr29...
                completed with rc=0 in 600 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 200 nano sec.
        for library jclse29...
                completed with rc=0 in 100 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 100 nano sec.
        for library VMInitStages...
                completed with rc=0 in 200 nano sec.
        for library threadInitStages...
                completed with rc=0 in 100 nano sec.

Checking results for stage TRACE_ENGINE_INITIALIZED

Running initialization stage JIT_INITIALIZED
        for library j9jit29...
                completed with rc=0 in 81187000 nano sec.
        for library j9bcv29...
                completed with rc=0 in 600 nano sec.
        for library j9gc29...
                completed with rc=0 in 26200 nano sec.
        for library j9dyn29...
                completed with rc=0 in 200 nano sec.
        for library j9vrb29...
                completed with rc=0 in 46800 nano sec.
        for library j9dmp29...
                completed with rc=0 in 36500 nano sec.
        for library j9trc29...
                completed with rc=0 in 300 nano sec.
        for library j9shr29...
                completed with rc=0 in 11721300 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 123100 nano sec.
        for library jclse29...
                completed with rc=0 in 200 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 400 nano sec.
        for library VMInitStages...
                completed with rc=0 in 161500 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage JIT_INITIALIZED

Running initialization stage AGENTS_STARTED
        for library j9jit29...
                completed with rc=0 in 1200 nano sec.
        for library j9bcv29...
                completed with rc=0 in 500 nano sec.
        for library j9gc29...
                completed with rc=0 in 900 nano sec.
        for library j9dyn29...
                completed with rc=0 in 100 nano sec.
        for library j9vrb29...
                completed with rc=0 in 500 nano sec.
        for library j9dmp29...
                completed with rc=0 in 300 nano sec.
        for library j9trc29...
                completed with rc=0 in 400 nano sec.
        for library j9shr29...
                completed with rc=0 in 700 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 25800 nano sec.
        for library jclse29...
                completed with rc=0 in 200 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 100 nano sec.
        for library VMInitStages...

Initializing Xrun libraries:

Checking results for stage XRUN_INIT_STAGE
                completed with rc=0 in 203700 nano sec.
        for library threadInitStages...
                completed with rc=0 in 300 nano sec.

Checking results for stage AGENTS_STARTED

Running initialization stage ABOUT_TO_BOOTSTRAP
        for library j9jit29...
                completed with rc=0 in 1423000 nano sec.
        for library j9bcv29...
                completed with rc=0 in 200 nano sec.
        for library j9gc29...
                completed with rc=0 in 51900 nano sec.
        for library j9dyn29...
                completed with rc=0 in 200 nano sec.
        for library j9vrb29...
                completed with rc=0 in 600 nano sec.
        for library j9dmp29...
                completed with rc=0 in 300 nano sec.
        for library j9trc29...
                completed with rc=0 in 500 nano sec.
        for library j9shr29...
                completed with rc=0 in 600 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 1500 nano sec.
        for library jclse29...
                completed with rc=0 in 300 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 300 nano sec.
        for library VMInitStages...
                completed with rc=0 in 32100 nano sec.
        for library threadInitStages...
                completed with rc=0 in 100 nano sec.

Checking results for stage ABOUT_TO_BOOTSTRAP

Running initialization stage JCL_INITIALIZED
        for library j9jit29...
                completed with rc=0 in 1900 nano sec.
        for library j9bcv29...
                completed with rc=0 in 700 nano sec.
        for library j9gc29...
                completed with rc=0 in 19000 nano sec.
        for library j9dyn29...
                completed with rc=0 in 300 nano sec.
        for library j9vrb29...
                completed with rc=0 in 900 nano sec.
        for library j9dmp29...
                completed with rc=0 in 300 nano sec.
        for library j9trc29...
                completed with rc=0 in 600 nano sec.
        for library j9shr29...
                completed with rc=0 in 800 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 400 nano sec.
        for library jclse29...
                completed with rc=0 in 25430100 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 300 nano sec.
        for library VMInitStages...
                completed with rc=0 in 32400 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage JCL_INITIALIZED

Running initialization stage VM_INITIALIZATION_COMPLETE
        for library j9jit29...
                completed with rc=0 in 194300 nano sec.
        for library j9bcv29...
                completed with rc=0 in 400 nano sec.
        for library j9gc29...
                completed with rc=0 in 900 nano sec.
        for library j9dyn29...
                completed with rc=0 in 300 nano sec.
        for library j9vrb29...
                completed with rc=0 in 300 nano sec.
        for library j9dmp29...
                completed with rc=0 in 500 nano sec.
        for library j9trc29...
                completed with rc=0 in 212000 nano sec.
        for library j9shr29...
                completed with rc=0 in 600 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 700 nano sec.
        for library jclse29...
                completed with rc=0 in 2900 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 300 nano sec.
        for library VMInitStages...
                completed with rc=0 in 180700 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage VM_INITIALIZATION_COMPLETE
openjdk version "1.8.0_232-internal"
OpenJDK Runtime Environment (build 1.8.0_232-internal-jenkins_2019_11_08_15_35-b00)
Eclipse OpenJ9 VM (build gctimer-c380994c0, JRE 1.8.0 Windows Server 2019 amd64-64-Bit Compressed References 20191108_429 (JIT enabled, AOT enabled)
OpenJ9   - c380994c0
OMR      - fa59bff71
JCL      - 57ba4563034 based on jdk8u232-b09)

Running shutdown stage INTERPRETER_SHUTDOWN...
        for library j9jvmti29...
                completed with rc=0 in 1500 nano sec.
        for library j9jit29...
                completed with rc=0 in 513900 nano sec.
        for library j9bcv29...
                completed with rc=0 in 1200 nano sec.
        for library j9gc29...
                completed with rc=0 in 700 nano sec.
        for library j9dyn29...
                completed with rc=0 in 300 nano sec.
        for library j9vrb29...
                completed with rc=0 in 400 nano sec.
        for library j9dmp29...
                completed with rc=0 in 15600 nano sec.
        for library j9trc29...
                completed with rc=0 in 75000 nano sec.
        for library j9shr29...
                completed with rc=0 in 1800 nano sec.
        for library jclse29...
                completed with rc=0 in 1200 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 500 nano sec.
        for library VMInitStages...
                completed with rc=0 in 500 nano sec.
        for library threadInitStages...
                completed with rc=0 in 500 nano sec.

Checking results for stage INTERPRETER_SHUTDOWN

Running shutdown stage LIBRARIES_ONUNLOAD...
        for library j9jvmti29...
                completed with rc=0 in 11300 nano sec.
        for library j9jit29...
                completed with rc=0 in 95100 nano sec.
        for library j9bcv29...
                completed with rc=0 in 54100 nano sec.
        for library j9gc29...
                completed with rc=0 in 900 nano sec.
        for library j9dyn29...
                completed with rc=0 in 7300 nano sec.
        for library j9vrb29...
                completed with rc=0 in 2400 nano sec.
        for library j9dmp29...
                completed with rc=0 in 200 nano sec.
        for library j9trc29...
                completed with rc=0 in 2400 nano sec.
        for library j9shr29...
                completed with rc=0 in 82500 nano sec.
        for library jclse29...
                completed with rc=0 in 12800 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 100 nano sec.
        for library VMInitStages...
                completed with rc=0 in 300 nano sec.
        for library threadInitStages...
                completed with rc=0 in 100 nano sec.

Checking results for stage LIBRARIES_ONUNLOAD

Running shutdown stage HEAP_STRUCTURES_FREED...
        for library j9jvmti29...
                completed with rc=0 in 300 nano sec.
        for library j9jit29...
                completed with rc=0 in 700 nano sec.
        for library j9bcv29...
                completed with rc=0 in 200 nano sec.
        for library j9gc29...
                completed with rc=0 in 210300 nano sec.
        for library j9dyn29...
                completed with rc=0 in 100 nano sec.
        for library j9vrb29...
                completed with rc=0 in 6100 nano sec.
        for library j9dmp29...
                completed with rc=0 in 200 nano sec.
        for library j9trc29...
                completed with rc=0 in 300 nano sec.
        for library j9shr29...
                completed with rc=0 in 4914400 nano sec.
        for library jclse29...
                completed with rc=0 in 500 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 200 nano sec.
        for library VMInitStages...
                completed with rc=0 in 100 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage HEAP_STRUCTURES_FREED

Running shutdown stage GC_SHUTDOWN_COMPLETE...
        for library j9jvmti29...
                completed with rc=0 in 500 nano sec.
        for library j9jit29...
                completed with rc=0 in 800 nano sec.
        for library j9bcv29...
                completed with rc=0 in 800 nano sec.
        for library j9gc29...
                completed with rc=0 in 567400 nano sec.
        for library j9dyn29...
                completed with rc=0 in 200 nano sec.
        for library j9vrb29...
                completed with rc=0 in 600 nano sec.
        for library j9dmp29...
                completed with rc=0 in 17800 nano sec.
        for library j9trc29...
                completed with rc=0 in 900 nano sec.
        for library j9shr29...
                completed with rc=0 in 1400 nano sec.
        for library jclse29...
                completed with rc=0 in 600 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 300 nano sec.
        for library VMInitStages...
                completed with rc=0 in 500 nano sec.
        for library threadInitStages...
                completed with rc=0 in 200 nano sec.

Checking results for stage GC_SHUTDOWN_COMPLETE
Closing library j9jit29
Closing library j9gc29
Closing library j9vrb29
Closing library j9dmp29
Closing library j9shr29
Closing library j9jvmti29
Closing library jclse29
```

**Comment by pshipton** [comment]
Looks good, it printed the -version output.

**Comment by slide** [comment]
Are there any extended tests that would be good to run?

**Comment by pshipton** [comment]
There is a tutorial here for running some testing, but there are additional prereqs required.
https://github.com/eclipse/openj9/blob/master/test/README.md

**Comment by pshipton** [comment]
It assumes you've already done `git clone https://github.com/eclipse/openj9.git`

**Comment by pshipton** [comment]
@dmitripivkine this is the issue I was referring to. According to https://github.com/eclipse/openj9/issues/7725#issuecomment-551859297, it's blocking adoption of OpenJ9 by Jenkins. The problem is https://github.com/eclipse/openj9/issues/7725#issuecomment-551918937

**Comment by james-crowley** [comment]
@pshipton @slide Glad to see this issue is going well. Hopefully the extended tests run without issue!

**Comment by dmitripivkine** [comment]
@jason-hall 
Would you please take a look to this?
MetronomeAlarm implementation currently uses `timeSetEvent()` for Windows. This method has been deprecated with recommendation to use https://msdn.microsoft.com/en-us/library/ms682485(v=vs.85) instead

@amicic FYI

**Comment by slide** [comment]
I have not been able to create a docker image to run the extended tests yet. I will continue to try it and paste it here when/if I do for future reference.

**Comment by dmitripivkine** [comment]
@slide Would you please try again? I believe problem has been fixed

**Comment by slide** [comment]
Is there a specific release you would like me to try?

**Comment by slide** [comment]
By the way, the issue with creating a docker container to run the tests with nanoserver is that cygwin doesn't run on nanoserver, nothing to do with openj9.

**Comment by dmitripivkine** [comment]
This is latest Java 8 Windows 32-bit nightly build from Adopt: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-12-11-19-45/OpenJDK8U-jdk_x86-32_windows_openj9_2019-12-11-19-45.zip

**Comment by dmitripivkine** [comment]
Closing this issue. Please reopen if there are any concerns left
