### ISSUE TITLE
shrtest_win_SE80_0 ASSERTION FAILED ** at CacheMap.cpp:7807

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7827]
Failing in OMR acceptance build.

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR/350
shrtest_win_SE80_0
```
----------------------------------------
AttachedData Test
----------------------------------------


AttachedDataTest test begin...


	INFO: AttachedDataTest.cpp(1852) testAttachedData Running test with cacheType: 1 and readOnly: 0
	18:36:26.805 0x5d28e00   j9shr.1012   *   ** ASSERTION FAILED ** at CacheMap.cpp:7807: (((UDATA)((struct J9UTF8*) (((uint8_t *) &((romClass)->className)) + (J9SRP)((romClass)->className))) < romClassEnd))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2019/11/21 12:36:26 - please wait.
JVMDUMP032I JVM requested System dump using 'C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR\openjdk-tests\TestConfig\test_output_15743583577103\shrtest_win_SE80_0\core.20191121.123626.4756.0001.dmp' in response to an event
JVMDUMP010I System dump written to C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR\openjdk-tests\TestConfig\test_output_15743583577103\shrtest_win_SE80_0\core.20191121.123626.4756.0001.dmp
JVMDUMP032I JVM requested Java dump using 'C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR\openjdk-tests\TestConfig\test_output_15743583577103\shrtest_win_SE80_0\javacore.20191121.123626.4756.0002.txt' in response to an event
JVMDUMP010I Java dump written to C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR\openjdk-tests\TestConfig\test_output_15743583577103\shrtest_win_SE80_0\javacore.20191121.123626.4756.0002.txt
JVMDUMP032I JVM requested Snap dump using 'C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR\openjdk-tests\TestConfig\test_output_15743583577103\shrtest_win_SE80_0\Snap.20191121.123626.4756.0003.trc' in response to an event
JVMDUMP010I Snap dump written to C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR\openjdk-tests\TestConfig\test_output_15743583577103\shrtest_win_SE80_0\Snap.20191121.123626.4756.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".
```

**Comment by pshipton** [comment]
@hangshao0 can you pls take a look.

**Comment by hangshao0** [comment]
Will look at this

**Comment by hangshao0** [comment]
```
18:36:26.797685302  0x05d28e00 j9shr.1576          Event       API j9shr_classStoreTransaction_createSharedClass : Allocated ROMClass at 0x7f4f000
18:36:26.797692546  0x05d28e00 j9shr.1278          Exit       <CC enterReadWriteAreaMutex (ERROR): POST enter readWrite mutex, rc=-1
18:36:26.797705339  0x05d28e00 j9shr.1578          Event       API j9shr_classStoreTransaction_createRomClassOnly : Info: enterStringTableMutex() failed. localRuntimeFlags=0x-7fefdffe135dfd45 stringTableBytes=0 readOnly=0 localRebuild=0 cacheRebuild=0 classname=java/lang/Object
18:36:26.797712407  0x05d28e00 j9shr.1577          Exit       <API j9shr_classStoreTransaction_createSharedClass : exiting with retval=0
18:36:26.797720531  0x05d28e00 j9shr.1487          Event       API j9shr_classStoreTransaction_updateSharedClassSize : Change size of class java/lang/Object to 1128
18:36:26.797727375  0x05d28e00 j9shr.1455          Entry      >API j9shr_classStoreTransaction_stop : enter (transactionState=2)
18:36:26.797734732  0x05d28e00 j9shr.1012          Assert     * ** ASSERTION FAILED ** at CacheMap.cpp:7807: (((UDATA)((struct J9UTF8*) (((uint8_t *) &((romClass)->className)) + (J9SRP)((romClass)->className))) < romClassEnd))
```

```
!j9romclass 0x7f4f000
J9ROMClass at 0x7f4f000 {
  Fields for J9ROMClass:
        0x0: U32 romSize = 0x00000468 (1128)
        0x4: U32 singleScalarStaticCount = 0x00000000 (0)
        0x8: J9SRP(J9UTF8) className = !j9utf8 0x07FA54D6
        ...
        ...
}

```

The class name 0x07FA54D6 is pointing to free pace in the shared cache. We have seen this once before, that's is why we added this assertion.

**Comment by hangshao0** [comment]
I can find the uft8 (java/lang/Object) in the shared intern table:
`
27.     Shared Table Entry < !J9SharedInternSRPHashTableEntry 0x05DF4E00 Flags: 0x0004 IWeight: 65535 IsUTF8Shared: true>       UTF8 <Add: 0x05E0C4C6 Data: "java/lang/Object">`

**Comment by hangshao0** [comment]
One thing I notice is that after I download the SDK from:
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-32_windows_OMR/397/OpenJ9-JDK8-x86-32_windows-20191121-165156.tar.gz. 

There is no .pdb files in the SDK, so I cannot see the debug symbols from windbg. Is there a reason why we don't inlcude the .pdb files in the SDK ? @pshipton @DanHeidinga

**Comment by pshipton** [comment]
I believe this is the default for an OpenJDK build. It would make sense to include debugging info in the builds done at OpenJ9 so we can more easily diagnose problems.

**Comment by hangshao0** [comment]
The shrtest is started up with a normal cache and read the shared intern table in the normal cache.
Inside AttachedDataTest::openTestCache(), 
https://github.com/eclipse/openj9/blob/master/runtime/tests/shared/AttachedDataTest.cpp#L175
it replaced sharedClassConfig->sharedClassCache with a heap allocated test cache. Then it stored java/lang/Object into the test cache. However, the shared string intern table being used is the one in the normal cache, causing the class name SPR to be incorrect. 

I found 3 romclasses of romclass/lang/Object in the core:

1.  In the pre-existing cache:
J9ROMClass at 0x5e0c000 {
  Fields for J9ROMClass:
        0x0: U32 romSize = 0x00000660 (1632)
        0x4: U32 singleScalarStaticCount = 0x00000000 (0)
        **0x8: J9SRP(J9UTF8) className = !j9utf8 0x05E0C4C6**
         ...
}

2. Another one:
J9ROMClass at 0x5db5ff0 {
  Fields for J9ROMClass:
        0x0: U32 romSize = 0x00000468 (1128)
        0x4: U32 singleScalarStaticCount = 0x00000000 (0)
        **0x8: J9SRP(J9UTF8) className = !j9utf8 0x05E0C4C6**
      .....
}

3. The incorrect one in the test cache that causes the assertion failure here at 0x7f4f000 

SRPs of classname in ROMClasses 0x5e0c000 and 0x5db5ff0  are correct. 

Looking at the value className filed of 0x7f4f000 and 0x5db5ff0, They are both 000564CE. 
So the test might have directly copy the romclass 0x5db5ff0 into 0x7f4f000 without fixing the SRPs.
xx 0x7f4f000,20,20
0x07f4f000 :  00000468 00000000 **000564CE** 00000000 [ h........d......]
0x07f4f010 :  00000021 08E00000 00000000 0000010C [ !...............]

xx 0x5db5ff0,20,20
0x05db5ff0 :  00000468 00000000 **000564CE** 00000000 [ h........d......]
0x05db6000 :  00000021 08E00000 00000000 0000010C [ !...............]
.

**Comment by hangshao0** [comment]
Found the cache header of the normal cache:

j9sharedcacheheader 0x5df00f0
J9SharedCacheHeader at 0x5df00f0 {
  Fields for J9SharedCacheHeader:
        0x0: U32 totalBytes = 0x00FFFF10 (16776976)
        0x4: U32 readWriteBytes = 0x0001BF10 (114448)
        0x8: U32 updateSRP = 0x00645858 (6576216)
        0xc: U32 readWriteSRP = 0x000000D4 (212)
        0x10: U32 segmentSRP = 0x00645458 (6575192)
        0x14: U32 updateCount = 0x00002CE2 (11490)
        0x18: J9WSRP(UDATA) updateCountPtr = 0x00002CE2 (11490)
        0x1c: volatile U32 readerCount = 0x00000000 (0)
        0x20: U32 unused2 = 0x00000000 (0)
        0x24: U32 writeHash = 0x00000000 (0)
        0x28: U32 unused3 = 0x00000000 (0)
        0x2c: U32 unused4 = 0x00000000 (0)
        0x30: U32 crashCntr = 0x00000000 (0)
        0x34: U32 aotBytes = 0x00509250 (5280336)
        0x38: U32 jitBytes = 0x00025768 (153448)
        **0x3c: U16 vmCntr = 0x03D7 (983)**
        0x3e: U8 corruptFlag = 0x00 (0)
        0x3f: U8 roundedPagesFlag = 0x01 (1)
        0x40: I32 minAOT = 0xFFFFFFFF (-1)
        0x44: I32 maxAOT = 0xFFFFFFFF (-1)
        0x48: U32 locked = 0x00000000 (0)
        0x4c: J9WSRP(U32) lockedPtr = 0x00000000 (0)
        0x50: J9WSRP(U8) corruptFlagPtr = 0x00 (0)
        0x54: J9SRP(J9SharedInternSRPHashTableEntry) sharedStringHead = !j9sharedinternsrphashtableentry 0x05E02618
        0x58: J9SRP(J9SharedInternSRPHashTableEntry) sharedStringTail = !j9sharedinternsrphashtableentry 0x05E09DB4
        0x5c: I32 unused1 = 0x00000000 (0)
        0x60: U32 totalSharedStringNodes = 0x0000128F (4751)
        0x64: U32 totalSharedStringWeight = 0x03E7E626 (65529382)
        0x68: U32 readWriteFlags = 0x00000001 (1)
        0x6c: U32 readWriteCrashCntr = 0x00000000 (0)
        0x70: U32 readWriteRebuildCntr = 0x00000000 (0)
        0x74: U32 osPageSize = 0x00001000 (4096)
        0x78: U32 ccInitComplete = 0x00000003 (3)
        0x7c: U32 crcValid = 0x00000003 (3)
        0x80: U32 crcValue = 0x24C2BAE6 (616741606)
        0x84: U32 containsCachelets = 0x00000000 (0)
        0x88: U32 cacheFullFlags = 0x0000000F (15)
        0x8c: U32 readWriteVerifyCntr = 0x00000000 (0)
        0x90: U32 extraFlags = 0x0000006C (108)
        0x94: U32 debugRegionSize = 0x00145000 (1331200)
        0x98: U32 lineNumberTableNextSRP = 0x00F4067A (15992442)
        0x9c: U32 localVariableTableNextSRP = 0x00FEE82C (16705580)
        0xa0: I32 minJIT = 0xFFFFFFFF (-1)
        0xa4: I32 maxJIT = 0xFFFFFFFF (-1)
        0xa8: I32 sharedInternTableBytes = 0x0001BE3C (114236)
        0xac: I32 corruptionCode = 0x00000000 (0)
        0xb0: U32 corruptValue = 0x00000000 (0)
        0xb4: U32 lastMetadataType = 0x020F0008 (34537480)
        0xb8: U32 writerCount = 0x00000000 (0)
        0xbc: U32 unused5 = 0x00000000 (0)
        0xc0: U32 unused6 = 0x00000000 (0)
        0xc4: U32 softMaxBytes = 0xFFFFFFFF (4294967295)
        0xc8: U32 unused8 = 0x00000000 (0)
        0xcc: U32 unused9 = 0x00000000 (0)
        0xd0: U32 unused10 = 0x00000000 (0)
}

OSCache_header2 0x05df0008
OSCache_header2 at 0x5df0008 {
  Fields for OSCache_header2:
        0x0: class J9PortShcVersion versionData = !j9portshcversion 0x05DF0008
        0x18: U32 size = 0x01000000 (16777216)
        0x1c: I32 dataStart = 0x000000CC (204)
        0x20: U32 dataLength = 0x00FFFF10 (16776976)
        0x24: U32 generation = 0x00000029 (41)
        0x28: U32 cacheInitComplete = 0x00000001 (1)
        **0x30: U64 buildID = 0x00000007E2D23800 (33870198784)**
        0x38: U32[] unused32 = !j9x 0x05DF0040
        0x50: U64[] unused64 = !j9x 0x05DF0058
}

It is a cache (100% full) left behind by an previous build that has a different sha: https://github.com/eclipse/openj9/commit/7E2D23800. 

This build/test failed to delete the exiting cache on the system before running this test.

**Comment by pshipton** [comment]
I notice the following "Failed to remove" messages in some test output, although they didn't cause any test failures.
```
[2019-11-21T17:45:58.282Z] JVMSHRC241E Error: unable to delete shared class cache file
[2019-11-21T17:45:58.282Z] JVMSHRC336E Port layer error code = -100
[2019-11-21T17:45:58.282Z] JVMSHRC337E Platform error message: (32) The process cannot access the file because it is being used by another process.
[2019-11-21T17:45:58.282Z] JVMSHRC430I Failed to remove current generation of shared class cache "sharedcc_LOCAL SERVICE"
```

**Comment by hangshao0** [comment]
> So the test might have directly copied the romclass at 0x5db5ff0 into 0x7f4f000 without fixing the SRPs.

Yes, the test is doing the memory copy
https://github.com/eclipse/openj9/blob/master/runtime/tests/shared/AttachedDataTest.cpp#L163
	`memcpy(newromclass,romclass,romclassSize);`

This is a test issue.

**Comment by hangshao0** [comment]
> I believe this is the default for an OpenJDK build. It would make sense to include debugging info in the builds done at OpenJ9 so we can more easily diagnose problems.

Issue opened here https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/155

**Comment by pshipton** [comment]
@hangshao0 I think we can close this as it's resolved by #7904, do you agree?

**Comment by hangshao0** [comment]
#7904 does not fix this issue. I think we need to skip the UTF8 SRP checks for AttachedDataTest.
