### ISSUE TITLE
Incompatible class change error

### ISSUE THREAD

**Issue by ocafebabe** [eclipse/openj9#8532]
Hi,

I'm trying to use Wildfly (8.2.1) with OpenJ9 but I get an exception during server startup:

```
Caused by: java.lang.IncompatibleClassChangeError
	at java.security.AccessController.doPrivileged(AccessController.java:678) [rt.jar:1.8.0_242]
	at org.jboss.weldx.transaction.UserTransaction$1780646979$Proxy$_$$_Weld$Proxy$.<clinit>(Unknown Source)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method) [rt.jar:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:1852) [rt.jar:1.8.0_242]
	at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
	at java.security.AccessController.doPrivileged(AccessController.java:734) [rt.jar:1.8.0_242]
	at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:303)
	at org.jboss.weld.bean.builtin.ee.AbstractEEBean.<init>(AbstractEEBean.java:36)
	at org.jboss.weld.bean.builtin.ee.UserTransactionBean.<init>(UserTransactionBean.java:50)
	at org.jboss.weld.bootstrap.BeanDeployment.createBeans(BeanDeployment.java:251)
	at org.jboss.weld.bootstrap.WeldStartup.deployBeans(WeldStartup.java:386)
	at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:83)
	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:92)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	... 3 more
```

This is the OpenJ9 build I'm using:

```
> java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200122_511 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)`
```

Is there any workaround to fix this error or it's a known issue?

Thanks

**Comment by DanHeidinga** [comment]
@ocafebabe Can you provide the full stack trace?  The lines that map to the `... 3 more` would help to identify if this is a known issue or not.

If you can provide detailed steps on how to reproduce the issue, we may be able to recreate it and get it fixed

**Comment by ocafebabe** [comment]
@DanHeidinga it's already the full stack trace! I'll try to create a simple test case to reproduce the problem...

**Comment by ocafebabe** [comment]
@DanHeidinga here are the steps to reproduce the issue:

**Download Wildfly 8.2.1 here:** https://download.jboss.org/wildfly/8.2.1.Final/wildfly-8.2.1.Final.tar.gz

1. unpack the archive to a temporary directory (that we'll call _<WILDFLY_DIR>_)
2. edit this file: _<WILDFLY_DIR>_/bin/standalone.conf and uncomment the **JAVA_HOME** variable
3. set **JAVA_HOME** to the OpenJ9 installation directory (see my initial comment for the version)

**Deploy a sample Java EE application to reproduce the issue:**

1. git clone https://github.com/weld/core.git
2. cd core/examples/jsf/numberguess/
3. mvn clean install
4. cd target
5. cp weld-numberguess.war _<WILDFLY_DIR>_/standalone/deployments/

**Start the Wildfly application server:**

1. cd _<WILDFLY_DIR>_/bin
2. ./standalone.sh

Then you should get the same exception as the one I posted initially!

**Comment by JasonFengJ9** [comment]
Reproduced the `IncompatibleClassChangeError`, `AccessController.doPrivileged()` expects an `java.security.PrivilegedAction` object but received an `org.jboss.weld.security.GetDeclaredMethodAction` which doesn't implement  the interface `PrivilegedAction()`.

Since `doPrivileged(PrivilegedAction)` is a public API in the specification,  it seems `GetDeclaredMethodAction` instantiation somehow was tied to `Hotspot` and generates incompatible `GetDeclaredMethodAction` object for `OpenJ9`.

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Do you have the type hierarchy for `GetDeclaredMethodAction`?

**Comment by DanHeidinga** [comment]
[1] GetDeclaredMethodAction - https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/security/GetDeclaredMethodAction.java

[2] AbstractReflectionAction - https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/security/AbstractReflectionAction.java

There's code in [1] to wrap the GetDeclaredMethodAction in a PrivilegedAction.

We should look at the code to figure out why the wrapping isn't happening there.  Issue in Weld?  Otherwise, I'm not sure how this would work on any JDK

**Comment by JasonFengJ9** [comment]
> https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/security/GetDeclaredMethodAction.java

Yeah, this is the code I was looking at as well though the actual code in the package is probably from a branch.
I suspect the behaviour difference might come from `AbstractReflectionAction.javaClass`. An instance returning from `GetDeclaredMethodAction. wrapException` has proper interface. https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/security/GetDeclaredMethodAction.java#L37 

Looking into how that `GetDeclaredMethodAction` instance was passed into `AccessController.doPrivileged()`.

**Comment by JasonFengJ9** [comment]
Summary of the investigation so far:

1. The object passing to `AccessController.doPrivileged(PrivilegedAction<T> action)` is `org.jboss.weld.security.GetDeclaredMethodAction` which actually is an `PrivilegedExceptionAction`. This indicates that `GetDeclaredMethodAction.of()` was invoked [1];
2. There was a PR (~5 years ago) "WELD-1828 Weld doesn't work on IBM JDK" [2] which appears to invoke `GetDeclaredMethodAction.wrapException()` to return a `PrivilegedAction` object if `NoSuchMethodException` is thrown as per the comment [3];
3. Part of PR [2] is an additional method `ReflectionLogger.noSuchMethodWrapper()` [4] which appears not in the class file coming with `weld-core-impl-2.2.6.Final.jar`;
4. Not able to locate the source code for `org.jboss.weldx.transaction.UserTransaction$1216203615$Proxy$_$$_Weld$Proxy$.<clinit>(Unknown Source)` which probably decides what `Action` object was created.

@ocafebabe do you have any insights about the item 3 or 4?

[1] https://github.com/weld/core/blob/67b4dffc00cc827143ce04eb900b95075337f668/impl/src/main/java/org/jboss/weld/security/GetDeclaredMethodAction.java#L28-L30
[2] https://github.com/weld/core/commit/ddb62bf69d8b038b70846da5e3b6cfc67fca3774
[3] https://github.com/weld/core/blob/67b4dffc00cc827143ce04eb900b95075337f668/impl/src/main/java/org/jboss/weld/security/GetDeclaredMethodAction.java#L33
[4] https://github.com/weld/core/blob/67b4dffc00cc827143ce04eb900b95075337f668/impl/src/main/java/org/jboss/weld/logging/ReflectionLogger.java#L114-L115

**Comment by ocafebabe** [comment]
@JasonFengJ9 sorry, not at all except that it's the JBoss reference implementation for CDI (context dependency injection) and that it's used by many different application servers (Wildfly, GlassFish/Payara, WebLogic, etc.)!

I don't know if it can help you, but I did another test with another Wildfly version, released right after the one I'm using (9.0.0-Final) and this time it worked! No errors during startup and the sample application was deployed successfully! Next, I've compared the Weld version between both releases:

**8.2.1-Final:**
./modules/system/layers/base/org/jboss/weld/core/main/weld-core-impl-2.2.6.Final.jar

**9.0.0-Final:**
./modules/system/layers/base/org/jboss/weld/core/main/weld-core-impl-2.2.14.Final.jar

If we can perhaps isolate the code differences of the Weld core component between these versions, we could have a better understanding of why it's not working under OpenJ9?

**Comment by JasonFengJ9** [comment]
@ocafebabe thanks for the updates! Good to know that `9.0.0-Final` works with `OpenJ9`.

The class `org.jboss.weld.logging.ReflectionLogger` in `weld-core-impl-2.2.14.Final.jar` does have the method `noSuchMethodWrapper`. I think this made the difference.
It appears `weld-core-impl-2.2.6.Final.jar` just missed one part of the PR https://github.com/weld/core/commit/ddb62bf69d8b038b70846da5e3b6cfc67fca3774.

I noticed that `Weld 2.2.14.Final` is also ~5 years old which is around the time that PR was introduced, out of curiosity, any particularly reason to choose an old build?

**Comment by ocafebabe** [comment]
I've found more details about WELD-1828 here: https://issues.redhat.com/browse/WELD-1828

But there's something I don't understand: the issue was initially detected on the **IBM JDK 7**, how come this issue is still present on OpenJ9 (which is built on top of the **OpenJDK**)?

**Comment by JasonFengJ9** [comment]
> WELD-1828 here: https://issues.redhat.com/browse/WELD-1828

Right, that was fixed by https://github.com/weld/core/commit/ddb62bf69d8b038b70846da5e3b6cfc67fca3774
But `weld-core-impl-2.2.6.Final.jar` doesn't include the complete changeset.

If you agree that the `IncompatibleClassChangeError` doesn't present in `Weld 2.2.14.Final` and beyond, can this issue be closed?

**Comment by ocafebabe** [comment]
Well, it doesn't really solve my problem as I can't use the new Weld version without upgrading the whole application server (which is not an option)!

**Comment by JasonFengJ9** [comment]
> I can't use the new Weld version without upgrading the whole application server 

Sorry to hear that. I see two options:
1. Rebuild `weld-core-impl-2.2.6.Final.jar` from source with https://github.com/weld/core/commit/ddb62bf69d8b038b70846da5e3b6cfc67fca3774;
2. Check the history of the file affected, if there is no other dependency changes, replace the classes within `weld-core-impl-2.2.6.Final.jar` with those in `weld-core-impl-2.2.14.Final.jar`.

If you experience any JVM related failure with the modified jar file, please post the stacktrace and the jar file here, we are happy to help.

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Any idea why this works on HotSpot and not OpenJ9?  If we understand the difference there may be something we can do to paper over the difference...

**Comment by JasonFengJ9** [comment]
> Any idea why this works on HotSpot and not OpenJ9?

The `GetDeclaredMethodAction` in question was implemented with `PrivilegedExceptionAction` interface, the `JBoss CDI` code intends to invoke `AccessController.doPrivileged(PrivilegedExceptionAction<T> action)` but it finds `OpenJ9 AccessController.doPrivileged(PrivilegedAction<T> action)` instead.

The bytecode in question is:
```
Signature: org/jboss/weldx/transaction/UserTransaction$1540596880$Proxy$_$$_Weld$Proxy$.<clinit>()V !bytecodes 0x00000000039B07D0
ROM Method: !j9rommethod 0x00007F57E447093C
> !bytecodes 0x00000000039B07D0
  Name: <clinit>
  Signature: ()V
  Access Flags (61000008): default static 
  Max Stack: 6
  Argument Count: 0
  Temp Count: 1

    0 ldc 1 (java.lang.Class) java/lang/Object
    2 ldc 2 (java.lang.String) toString
    4 iconst0 
    5 anewarray 23 java/lang/Class
    8 invokestatic 25 org/jboss/weld/security/GetDeclaredMethodAction.of(Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Class;)Lorg/jboss/weld/security/GetDeclaredMethodAction;
   11 invokestatic 27 java/security/AccessController.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object;
```
An `IncompatibleClassChangeError` was thrown at `Bytecode index = 11`.

The logic generating these bytecode is deeply buried within `JBoss CDI`.

Will have to dig into more `JBoss` code.

**Comment by JasonFengJ9** [comment]
This problem can be reproduced via a standalone testcase built from a `jasm` file and a normal java file (not included):
```
super public class a/se/java_security/MydoPriv
           version 52:0
{
    public Method "<init>":"()V" stack 1 locals 1 {
        aload_0;
        invokespecial Method a/se/java_security/MydoPriv."<init>":"()V";
        return;
    }

    public static Method method:"()Ljava/lang/String;" stack 16 locals 4 {
        invokestatic Method a/se/java_security/TestRIAccdoPriv."getPEA":"()Ljava/security/PrivilegedExceptionAction;";
        invokestatic Method java/security/AccessController."doPrivileged":"(Ljava/security/PrivilegedAction;)Ljava/lang/Object;";
        ldc String "FAILED: this should NOT be called";
        areturn;
    }
}
```
Throwing `IncompatibleClassChangeError` is correct when invoking `AccessController.doPrivileged(PrivilegedAction<T> action)` with an `PrivilegedExceptionAction` object.

@DanHeidinga indicates that `Hotspot JVM` allows such invocation because its `native method AccessController.doPrivileged()` doesn't check the incoming parameter types.  This behaviour appears a bug and we are making an arrangement to report it to `OpenJDK` community.

@ocafebabe `OpenJ9 JVM` behaviour is expected, no change will be made in JVM side to circumvent the `IncompatibleClassChangeError`. Please consider the options mentioned in https://github.com/eclipse/openj9/issues/8532#issuecomment-584980090.

**Comment by ocafebabe** [comment]
@JasonFengJ9 ok no worries, thanks a lot for your time and investigations!
