### ISSUE TITLE
JDK8 JIT Server : ASSERTION FAILED ** at swalk.c:1565: ((0 ))

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9022]
Failure link
------------

From an internal build `Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/32`
```
22:10:26  openjdk version "1.8.0_252-internal"
22:10:26  OpenJDK Runtime Environment (build 1.8.0_252-internal-jenkins_2020_03_28_18_43-b00)
22:10:26  Eclipse OpenJ9 VM (build ibm_sdk-0852f80a4a, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200328_33 (JIT enabled, AOT enabled)
22:10:26  OpenJ9   - 0852f80a4a
22:10:26  OMR      - e9bed7888
22:10:26  JCL      - 4f7bf238294 based on jdk8u252-b08)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
LT  22:20:44.400 - Final test list:
LT  22:20:44.400 -   0 ArbitraryJava[net.adoptopenjdk.test.util.calendars.CalendarTest run]  Weighting=1 
LT  22:20:44.400 -   1 ArbitraryJava[net.adoptopenjdk.test.util.hashmap.Hog run]  Weighting=1 
LT  22:20:44.400 -   2 JUnit[net.adoptopenjdk.test.util.lilac.TestArrays]  Weighting=1 
LT  22:20:44.400 -   3 JUnit[net.adoptopenjdk.test.util.solver.SolverTest]  Weighting=1 
LT  22:20:44.401 -   4 JUnit[net.adoptopenjdk.test.util.treemap.TreeMapAPITest]  Weighting=1 
LT  22:20:44.401 -   5 JUnit[net.adoptopenjdk.test.util.treemap.TreeMapTest]  Weighting=1 
LT  22:20:44.461 - Starting thread. Suite=0 thread=0
LT  22:20:44.466 - Starting thread. Suite=0 thread=1
LT  22:20:44.466 - Starting thread. Suite=0 thread=2
LT  stderr 
LT  stderr 
LT  stderr *** Invalid JIT return address 00000000FFEE267A in 00000000017BF408
LT  stderr 
LT  stderr 02:20:48.176 0x17bf100    j9vm.249    *   ** ASSERTION FAILED ** at swalk.c:1565: ((0 ))
LT  stderr JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/03/28 22:20:48 - please wait.
LT  stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15854479539478/HCRLateAttachWorkload_0/20200328-222040-HCRLateAttachWorkload/results/core.20200328.222048.23987.0001.dmp' in response to an event
```

To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=x86-64_linux&TARGET=HCRLateAttachWorkload_0

**Comment by pshipton** [comment]
@mpirvu fyi

**Comment by a7ehuo** [comment]
This looks like a duplicate issue of #8786. I reproduced it locally with the same backtrace mentioned in https://github.com/eclipse/openj9/issues/8786#issuecomment-600725761:  

```
(gdb) bt
#0  0x00007f713cff92d1 in pthread_kill () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f7137085e9d in omrdump_create ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so
#2  0x00007f7136b378e2 in doSystemDump ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9dmp29.so
#3  0x00007f7136b33625 in protectedDumpFunction ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9dmp29.so
#4  0x00007f7137068fd3 in omrsig_protect ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so
#5  0x00007f7136b36d4b in runDumpFunction ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9dmp29.so
#6  0x00007f7136b36edf in runDumpAgent ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9dmp29.so
#7  0x00007f7136b4dccb in triggerDumpAgents ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9dmp29.so
#8  0x00007f7137d0c322 in generateDiagnosticFiles ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9vm29.so
#9  0x00007f7137068fd3 in omrsig_protect ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so
#10 0x00007f7137d0c535 in vmSignalHandler ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9vm29.so
#11 0x00007f7137d39435 in swapStacksAndRunHandler ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9vm29.so
#12 0x00000000003d2f00 in ?? ()
#13 0x00007f7101b98b90 in ?? ()
#14 0x00007f7137ff6ec0 in initNameAndSig ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9vm29.so
--Type <RET> for more, q to quit, c to continue without paging--
#15 0x00000000ffdb1180 in ?? ()
#16 0x0000000000335300 in ?? ()
#17 0x0000000000000000 in ?? ()
```

**Comment by mpirvu** [comment]
@a7ehuo Now that #8786 is fixed, could you please verify that this issue is fixed as well? Thanks

**Comment by a7ehuo** [comment]
I don't see any crash at the client with the latest fix from #8786 (OpenJ9 - ffece8e) when running `HCRLateAttachWorkload_0` after ten runs. But I run into a server crash. I'm trying to run more times and see if it's consistent. 



```
#12 <signal handler called>
#13 0x00007fcdba81710e in std::_Hashtable<int, std::pair<int const, TR_OpaqueClassBlock*>, TR::typed_allocator<std::pair<int const, TR_OpaqueClassBlock*>, J9::PersistentAllocator&>, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_bucket_index (this=0x168, __k=@0x7fcdb7b65130: 7, __c=7)
    at /usr/include/c++/7/bits/hashtable.h:631
#14 0x00007fcdba81416d in std::_Hashtable<int, std::pair<int const, TR_OpaqueClassBlock*>, TR::typed_allocator<std::pair<int const, TR_OpaqueClassBlock*>, J9::PersistentAllocator&>, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find (this=0x168, __k=@0x7fcdb7b65130: 7) at /usr/include/c++/7/bits/hashtable.h:1424
#15 0x00007fcdba8116b3 in std::unordered_map<int, TR_OpaqueClassBlock*, std::hash<int>, std::equal_to<int>, TR::typed_allocator<std::pair<int const, TR_OpaqueClassBlock*>, J9::PersistentAllocator&> >::find (this=0x168, __x=@0x7fcdb7b65130: 7)
--Type <RET> for more, q to quit, c to continue without paging-- 
    at /usr/include/c++/7/bits/unordered_map.h:920
#16 0x00007fcdba805aa7 in TR_ResolvedJ9JITServerMethod::getClassFromConstantPool (this=0x7fcc8a7da280, comp=0x7fcc8a63a000, 
    cpIndex=7, returnClassForAOT=true)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/env/j9methodServer.cpp:189
#17 0x00007fcdba5e814c in TR_ResolvedMethod::getClassFromFieldOrStatic (this=0x7fcc8a7da2d8, comp=0x7fcc8a63a000, 
    cpIndex=19, returnClassForAOT=true)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/compile/ResolvedMethod.hpp:181
#18 0x00007fcdba9b2061 in J9::TransformUtil::canFoldStaticFinalField (comp=0x7fcc8a63a000, node=0x7fcc8a7f2430)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/optimizer/J9TransformUtil.cpp:1034
#19 0x00007fcdba9b1ef9 in J9::TransformUtil::foldReliableStaticFinalField (comp=0x7fcc8a63a000, node=0x7fcc8a7f2430)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/optimizer/J9TransformUtil.cpp:981
#20 0x00007fcdba9b3805 in J9::TransformUtil::transformDirectLoad (comp=0x7fcc8a63a000, node=0x7fcc8a7f2430)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/optimizer/J9TransformUtil.cpp:1485
#21 0x00007fcdbacec63c in directLoadSimplifier (node=0x7fcc8a7f2430, block=0x7fcc8a7c7260, s=0x7fcc8a8ea020)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRSimplifierHandlers.cpp:5467
#22 0x00007fcdbacdb74d in OMR::Simplifier::simplify (this=0x7fcc8a8ea020, node=0x7fcc8a7f2430, block=0x7fcc8a7c7260)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRSimplifier.cpp:521
#23 0x00007fcdbaceed5f in treetopSimplifier (node=0x7fcc8a7f4370, block=0x7fcc8a7c7260, s=0x7fcc8a8ea020)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRSimplifierHandlers.cpp:5990
#24 0x00007fcdbacdb74d in OMR::Simplifier::simplify (this=0x7fcc8a8ea020, node=0x7fcc8a7f4370, block=0x7fcc8a7c7260)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRSimplifier.cpp:521
#25 0x00007fcdbacdb5f4 in OMR::Simplifier::simplify (this=0x7fcc8a8ea020, treeTop=0x7fcc8a863a00, block=0x7fcc8a7c7260)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRSimplifier.cpp:480
#26 0x00007fcdbacdb502 in OMR::Simplifier::simplify (this=0x7fcc8a8ea020, block=0x7fcc8a7c7260)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRSimplifier.cpp:449
#27 0x00007fcdbacdb269 in OMR::Simplifier::simplifyExtendedBlock (this=0x7fcc8a8ea020, treeTop=0x7fcc8a7c7220)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRSimplifier.cpp:382
--Type <RET> for more, q to quit, c to continue without paging--
#28 0x00007fcdbacdacae in OMR::Simplifier::perform (this=0x7fcc8a8ea020)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRSimplifier.cpp:245
#29 0x00007fcdbacd4ac5 in OMR::Optimizer::performOptimization (this=0x7fcc8a6fae20, 
    optimization=0x7fcdbb105378 <cheapWarmStrategyOpts+216>, firstOptIndex=0, lastOptIndex=2147483647, doTiming=0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMROptimizer.cpp:2061
#30 0x00007fcdbacd187a in OMR::Optimizer::optimize (this=0x7fcc8a6fae20)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMROptimizer.cpp:1142
#31 0x00007fcdbaa777a5 in OMR::Compilation::performOptimizations (this=0x7fcc8a63a000)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/compile/OMRCompilation.cpp:1286
#32 0x00007fcdbaa767c8 in OMR::Compilation::compile (this=0x7fcc8a63a000)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/compile/OMRCompilation.cpp:1081
#33 0x00007fcdba56ce5c in TR::CompilationInfoPerThreadBase::compile (this=0x7fcdb9287740, vmThread=0x32100, 
    compiler=0x7fcc8a63a000, compilee=0x7fcdb7b68598, vm=..., optimizationPlan=0x7fcdb930cca0, scratchSegmentProvider=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/CompilationThread.cpp:9054
#34 0x00007fcdba56b040 in TR::CompilationInfoPerThreadBase::wrappedCompile (portLib=0x7fcdbdfb2320 <j9portLibrary>, 
    opaqueParameters=0x7fcdb7b68310)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/CompilationThread.cpp:8579
#35 0x00007fcdbc9bafd3 in omrsig_protect (portLibrary=0x7fcdbdfb2320 <j9portLibrary>, 
    fn=0x7fcdba568a24 <TR::CompilationInfoPerThreadBase::wrappedCompile(J9PortLibrary*, void*)>, fn_arg=0x7fcdb7b68310, 
    handler=0x7fcdba55516a <jitSignalHandler(J9PortLibrary*, U_32, void*, void*)>, handler_arg=0x32100, flags=249, 
    result=0x7fcdb7b682e0) at ../../omr/port/unix/omrsignal.c:425
#36 0x00007fcdba568577 in TR::CompilationInfoPerThreadBase::compile (this=0x7fcdb9287740, vmThread=0x32100, 
    entry=0x7fccb400d060, scratchSegmentProvider=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/CompilationThread.cpp:7690
#37 0x00007fcdba7b74bc in TR::CompilationInfoPerThreadRemote::processEntry (this=0x7fcdb9287740, entry=..., 
    scratchSegmentProvider=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/JITServerCompilationThread.cpp:635
#38 0x00007fcdba55ec0e in TR::CompilationInfoPerThread::processEntries (this=0x7fcdb9287740)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/CompilationThread.cpp:3926
--Type <RET> for more, q to quit, c to continue without paging--
#39 0x00007fcdba55e54a in TR::CompilationInfoPerThread::run (this=0x7fcdb9287740)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/CompilationThread.cpp:3797
#40 0x00007fcdba55e31f in protectedCompilationThreadProc (compInfoPT=0x7fcdb9287740)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/CompilationThread.cpp:3736
#41 0x00007fcdbc9bafd3 in omrsig_protect (portLibrary=0x7fcdbdfb2320 <j9portLibrary>, 
    fn=0x7fcdba55e14c <protectedCompilationThreadProc(J9PortLibrary*, TR::CompilationInfoPerThread*)>, 
    fn_arg=0x7fcdb9287740, handler=0x7fcdbd65e6d0 <structuredSignalHandler>, handler_arg=0x32100, flags=506, 
    result=0x7fcdb7b69da0) at ../../omr/port/unix/omrsignal.c:425
#42 0x00007fcdba55e0f5 in compilationThreadProc (entryarg=0x7fcdb9287740)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/CompilationThread.cpp:3641
#43 0x00007fcdbd3b81f2 in thread_wrapper (arg=0x55c51870a128) at ../omr/thread/common/omrthread.c:1705
#44 0x00007fcdbdb616db in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#45 0x00007fcdbe0d688f in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) fr 16
#16 0x00007fcdba805aa7 in TR_ResolvedJ9JITServerMethod::getClassFromConstantPool (this=0x7fcc8a7da280, comp=0x7fcc8a63a000, 
    cpIndex=7, returnClassForAOT=true)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/env/j9methodServer.cpp:189
189	      auto it = constantClassPoolCache.find(cpIndex);
(gdb) list -
184	
185	   TR::CompilationInfoPerThread *compInfoPT = _fe->_compInfoPT;
186	      {
187	      OMR::CriticalSection getRemoteROMClass(compInfoPT->getClientData()->getROMMapMonitor());
188	      auto &constantClassPoolCache = getJ9ClassInfo(compInfoPT, _ramClass)._constantClassPoolCache;
189	      auto it = constantClassPoolCache.find(cpIndex);
190	      if (it != constantClassPoolCache.end())
191	         return it->second;
192	      }
193	   _stream->write(JITServer::MessageType::ResolvedMethod_getClassFromConstantPool, _remoteMirror, cpIndex, returnClassForAOT);
(gdb) print cpIndex
$1 = 7

```

**Comment by a7ehuo** [comment]
Reproduced the server crash again while compiling a different method but it still crashed when accessing the cache at the server. This time it's accessing `_remoteROMStringsCache`. Last time https://github.com/eclipse/openj9/issues/9022#issuecomment-608654220 is accessing `_constantClassPoolCache`. looks `_ramClass` is empty. 


```
(gdb) fr 16
#16 0x00007f62985b59d2 in TR_ResolvedJ9JITServerMethod::getRemoteROMString (this=0x7f61678d4370, 
    len=@0x7f6295808150: 1738681872, basePtr=0x7f6170b798c0, offsets=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/env/j9methodServer.cpp:1040
1040	      auto gotStr = stringsCache.find(key);

(gdb) print *_ramClass
$3 = {eyecatcher = 0, romClass = 0x0, superclasses = 0x0, classDepthAndFlags = 0, classDepthWithFlags = 0, classFlags = 0, 
  classLoader = 0x0, classObject = 0x0, initializeStatus = 0, ramMethods = 0x0, ramStatics = 0x0, arrayClass = 0x0, 
  totalInstanceSize = 0, lastITable = 0x0, instanceDescription = 0x0, instanceLeafDescription = 0x0, 
  instanceHotFieldDescription = 0, selfReferencingField1 = 0, selfReferencingField2 = 0, initializerCache = 0x0, 
  romableAotITable = 0, packageID = 0, module = 0x0, subclassTraversalLink = 0x0, subclassTraversalReverseLink = 0x0, 
  iTable = 0x0, castClassCache = 0, jniIDs = 0x0, lockOffset = 0, paddingForGLRCounters = 0, reservedCounter = 0, 
  cancelCounter = 0, newInstanceCount = 0, backfillOffset = 0, replacedClass = 0x0, finalizeLinkOffset = 0, 
  nextClassInSegment = 0x0, ramConstantPool = 0x0, callSites = 0x0, methodTypes = 0x0, varHandleMethodTypes = 0x0, 
  customSpinOption = 0x0, staticSplitMethodTable = 0x0, specialSplitMethodTable = 0x0, jitMetaDataList = 0x0, gcLink = 0x0, 
  hostClass = 0x0, flattenedClassCache = 0x0}

(gdb) fr 58
#58 0x00007f6298318eac in TR::CompilationInfoPerThreadBase::compile (this=0x7f6296f2d740, vmThread=0xd08100, 
    compiler=0x7f61675f8000, compilee=0x7f629580e5f8, vm=..., optimizationPlan=0x7f61700ab070, scratchSegmentProvider=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/CompilationThread.cpp:9054
9054	         rtn = compiler->compile();

(gdb) print compiler->_signature
$14 = 0x7f61675f9a40 "java/net/URLStreamHandler.parseURL(Ljava/net/URL;Ljava/lang/String;II)V"
```

```
#12 <signal handler called>
#13 0x00007f62985c3f1c in std::_Hashtable<TR_RemoteROMStringKey, std::pair<TR_RemoteROMStringKey const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, TR::typed_allocator<std::pair<TR_RemoteROMStringKey const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, J9::PersistentAllocator&>, std::__detail::_Select1st, std::equal_to<TR_RemoteROMStringKey>, std::hash<TR_RemoteROMStringKey>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_bucket_index (this=0xa8, __k=..., __c=140056479373504) at /usr/include/c++/7/bits/hashtable.h:631
#14 0x00007f62985c1707 in std::_Hashtable<TR_RemoteROMStringKey, std::pair<TR_RemoteROMStringKey const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, TR::typed_allocator<std::pair<TR_RemoteROMStringKey const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, J9::PersistentAllocator&>, std::__detail::_Select1st, std::equal_to<TR_RemoteROMStringKey>, std::hash<TR_RemoteROMStringKey>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find
--Type <RET> for more, q to quit, c to continue without paging--
    (this=0xa8, __k=...) at /usr/include/c++/7/bits/hashtable.h:1424
#15 0x00007f62985be971 in std::unordered_map<TR_RemoteROMStringKey, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<TR_RemoteROMStringKey>, std::equal_to<TR_RemoteROMStringKey>, TR::typed_allocator<std::pair<TR_RemoteROMStringKey const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, J9::PersistentAllocator&> >::find (this=0xa8, __x=...) at /usr/include/c++/7/bits/unordered_map.h:920
#16 0x00007f62985b59d2 in TR_ResolvedJ9JITServerMethod::getRemoteROMString (this=0x7f61678d4370, 
    len=@0x7f6295808150: 1738681872, basePtr=0x7f6170b798c0, offsets=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/env/j9methodServer.cpp:1040
#17 0x00007f62985b5e74 in TR_ResolvedJ9JITServerMethod::getROMString (this=0x7f61678d4370, len=@0x7f6295808150: 1738681872, 
    basePtr=0x7f6170b798c0, offsets=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/env/j9methodServer.cpp:1090
#18 0x00007f62985b6188 in TR_ResolvedJ9JITServerMethod::fieldOrStaticNameChars (this=0x7f61678d4370, cpIndex=76, 
    len=@0x7f6295808150: 1738681872)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/env/j9methodServer.cpp:1162
#19 0x00007f62983a5a1a in TR_ResolvedJ9Method::fieldNameChars (this=0x7f61678d4370, cpIndex=76, 
    len=@0x7f6295808150: 1738681872)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/env/j9method.cpp:5898
#20 0x00007f6298bf0d72 in constrainIaload (vp=0x7f6167c28020, node=0x7f6167a22dc0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/VPHandlers.cpp:2797
#21 0x00007f6298bc6435 in OMR::ValuePropagation::launchNode (this=0x7f6167c28020, node=0x7f6167a22dc0, 
    parent=0x7f6167a22e60, whichChild=0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/ValuePropagationCommon.cpp:4169
#22 0x00007f6298c1663e in constrainChildren (vp=0x7f6167c28020, node=0x7f6167a22e60)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/VPHandlersCommon.cpp:73
#23 0x00007f6298bc6435 in OMR::ValuePropagation::launchNode (this=0x7f6167c28020, node=0x7f6167a22e60, parent=0x0, 
    whichChild=0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/ValuePropagationCommon.cpp:4169
#24 0x00007f6298bb8206 in OMR::ValuePropagation::processTrees (this=0x7f6167c28020, startTree=0x7f6167a57570, 
    endTree=0x7f6167a56a30)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/ValuePropagationCommon.cpp:642
--Type <RET> for more, q to quit, c to continue without paging--
#25 0x00007f6298aeda2c in TR::GlobalValuePropagation::processBlock (this=0x7f6167c28020, node=0x7f6167cc8000, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4697
#26 0x00007f6298aeb78d in TR::GlobalValuePropagation::processStructure (this=0x7f6167c28020, node=0x7f6167cc8000, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4094
#27 0x00007f6298aed054 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cc8000, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4563
#28 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cc81a0, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#29 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cc2690, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#30 0x00007f6298aeccce in TR::GlobalValuePropagation::processRegionSubgraph (this=0x7f6167c28020, node=0x7f6167cd26c0, 
    lastTimeThrough=true, insideLoop=false, isNaturalLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4479
#31 0x00007f6298aeb80a in TR::GlobalValuePropagation::processAcyclicRegion (this=0x7f6167c28020, node=0x7f6167cd26c0, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4103
#32 0x00007f6298aeb722 in TR::GlobalValuePropagation::processStructure (this=0x7f6167c28020, node=0x7f6167cd26c0, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4081
#33 0x00007f6298aed054 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd26c0, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4563
#34 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd28c0, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer--Type <RET> for more, q to quit, c to continue without paging--
/OMRValuePropagation.cpp:4510
#35 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd2a60, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#36 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd2cb0, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#37 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd2f80, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#38 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd3170, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#39 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd3620, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#40 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd3240, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#41 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd3360, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#42 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd3430, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#43 0x00007f6298aece43 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cd0e90, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4510
#44 0x00007f6298aeccce in TR::GlobalValuePropagation::processRegionSubgraph (this=0x7f6167c28020, node=0x7f6167cdaf50, 
    lastTimeThrough=true, insideLoop=false, isNaturalLoop=false)
--Type <RET> for more, q to quit, c to continue without paging--
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4479
#45 0x00007f6298aeb80a in TR::GlobalValuePropagation::processAcyclicRegion (this=0x7f6167c28020, node=0x7f6167cdaf50, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4103
#46 0x00007f6298aeb722 in TR::GlobalValuePropagation::processStructure (this=0x7f6167c28020, node=0x7f6167cdaf50, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4081
#47 0x00007f6298aed054 in TR::GlobalValuePropagation::processRegionNode (this=0x7f6167c28020, node=0x7f6167cdaf50, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4563
#48 0x00007f6298aeccce in TR::GlobalValuePropagation::processRegionSubgraph (this=0x7f6167c28020, node=0x7f62958090a0, 
    lastTimeThrough=true, insideLoop=false, isNaturalLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4479
#49 0x00007f6298aeb80a in TR::GlobalValuePropagation::processAcyclicRegion (this=0x7f6167c28020, node=0x7f62958090a0, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4103
#50 0x00007f6298aeb722 in TR::GlobalValuePropagation::processStructure (this=0x7f6167c28020, node=0x7f62958090a0, 
    lastTimeThrough=true, insideLoop=false)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4081
#51 0x00007f6298aeb5dc in TR::GlobalValuePropagation::determineConstraints (this=0x7f6167c28020)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:4063
#52 0x00007f6298aeac89 in TR::GlobalValuePropagation::perform (this=0x7f6167c28020)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMRValuePropagation.cpp:3812
#53 0x00007f6298a80b15 in OMR::Optimizer::performOptimization (this=0x7f61676e87b0, 
    optimization=0x7f6298fcd5a0 <cheapGlobalValuePropagationOpts+32>, firstOptIndex=0, lastOptIndex=2147483647, doTiming=0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMROptimizer.cpp:2061
#54 0x00007f6298a7f15b in OMR::Optimizer::performOptimization (this=0x7f61676e87b0, 
    optimization=0x7f6298eb1320 <cheapWarmStrategyOpts+96>, firstOptIndex=0, lastOptIndex=2147483647, doTiming=0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer--Type <RET> for more, q to quit, c to continue without paging--
/OMROptimizer.cpp:1607
#55 0x00007f6298a7d8ca in OMR::Optimizer::optimize (this=0x7f61676e87b0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/optimizer/OMROptimizer.cpp:1142
#56 0x00007f62988237f5 in OMR::Compilation::performOptimizations (this=0x7f61675f8000)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/compile/OMRCompilation.cpp:1286
#57 0x00007f6298822818 in OMR::Compilation::compile (this=0x7f61675f8000)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr/compiler/compile/OMRCompilation.cpp:1081
#58 0x00007f6298318eac in TR::CompilationInfoPerThreadBase::compile (this=0x7f6296f2d740, vmThread=0xd08100, 
    compiler=0x7f61675f8000, compilee=0x7f629580e5f8, vm=..., optimizationPlan=0x7f61700ab070, scratchSegmentProvider=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/CompilationThread.cpp:9054
```

**Comment by mpirvu** [comment]
>  looks _ramClass is empty

I assume that refers to `TR_ResolvedJ9JITServerMethod` and that is not supposed to happen as far as I remember. Could we place a check when such a data structure is fully created that _ramClass should not be NULL?

**Comment by a7ehuo** [comment]
> I assume that refers to TR_ResolvedJ9JITServerMethod and that is not supposed to happen as far as I remember.

Yes, it's `TR_ResolvedJ9JITServerMethod::_ramClass`. It shows it looks like empty when the crash happened. 
```
(gdb) print *_ramClass
$3 = {eyecatcher = 0, romClass = 0x0, superclasses = 0x0, classDepthAndFlags = 0, classDepthWithFlags = 0, classFlags = 0, 
  classLoader = 0x0, classObject = 0x0, initializeStatus = 0, ramMethods = 0x0, ramStatics = 0x0, arrayClass = 0x0, 
  totalInstanceSize = 0, lastITable = 0x0, instanceDescription = 0x0, instanceLeafDescription = 0x0, 
  instanceHotFieldDescription = 0, selfReferencingField1 = 0, selfReferencingField2 = 0, initializerCache = 0x0, 
  romableAotITable = 0, packageID = 0, module = 0x0, subclassTraversalLink = 0x0, subclassTraversalReverseLink = 0x0, 
  iTable = 0x0, castClassCache = 0, jniIDs = 0x0, lockOffset = 0, paddingForGLRCounters = 0, reservedCounter = 0, 
  cancelCounter = 0, newInstanceCount = 0, backfillOffset = 0, replacedClass = 0x0, finalizeLinkOffset = 0, 
  nextClassInSegment = 0x0, ramConstantPool = 0x0, callSites = 0x0, methodTypes = 0x0, varHandleMethodTypes = 0x0, 
  customSpinOption = 0x0, staticSplitMethodTable = 0x0, specialSplitMethodTable = 0x0, jitMetaDataList = 0x0, gcLink = 0x0, 
  hostClass = 0x0, flattenedClassCache = 0x0}
```

The issue is quite intermittent. after rebasing to newer builds and so far the server crash hasn't occurred yet after ten runs. 
```
OpenJ9   - ad97b5d
OMR      - 9d422b0
JCL      - f80a8d6 based on jdk8u252-b05)
```

**Comment by a7ehuo** [comment]
This should be fixed by now. Also validated in the Grinder (https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7195/) for 100 runs. All pass.

**Comment by mpirvu** [comment]
Closing as per comment above
